### PR TITLE
Custom receiver address for `ft-transfer` CLI

### PR DESCRIPTION
**Pull request by adizere**
Closes: #806
Closes: #628 

## Description

- `hermes tx raw ft-transfer ibc-0 ibc-1 transfer channel-2 9999 1000 -n 1 -r board:1938586739`

>{"timestamp":"Apr 08 16:14:17.305","level":"INFO","fields":..... amount: 9999, denom: \"samoleans\", receiver: Some(\"board:1938586739\"), ...

> {"status":"success",....

______

For contributor use:

- [X] Updated the __Unreleased__ section of [CHANGELOG.md](https://github.com/informalsystems/ibc-rs/blob/master/CHANGELOG.md) with the issue.
- [ ] If applicable: Unit tests written, added test to CI.
- [ ] Linked to Github issue with discussion and accepted design OR link to spec that describes this work.
- [ ] Updated relevant documentation (`docs/`) and code comments.
- [ ] Re-reviewed `Files changed` in the Github PR explorer.

### CODE REVIEW

**Comment by adizere** [comment]
@michaelfig when you have time could you have a look over this?

**Comment by andynog** [comment]
Also @michaelfig could you please clarify the requirements. My understanding is that the receiver address on the destination chain can be any string (not a bech32 address) but the signer of the tx is a bech32 address. Is that correct?

**Comment by michaelfig** [comment]
> Also @michaelfig could you please clarify the requirements. My understanding is that the receiver address on the destination chain can be any string (not a bech32 address) but the signer of the tx is a bech32 address. Is that correct?

That's correct!  Agoric will be enabling bech32 receivers for compatibility with wallets (like Keplr) that make assumptions of the chain's configuration, but we will also support differently-formatted names (like `board:...`) for more fine-grained control of the deposit destination.  It would be great if Hermes could support them both.

I will have a look at the PR now....

**Review by michaelfig — COMMENTED** [review]
I can't read Rust very well, but allowing the receiver as an option looks right.

Not sure what the `custom_signer` is needed for.  Is it converting the receiver string to bech32?  If so, that's almost certainly not right.  The receiver (say `xyz`) option should be copied directly into the ics20-1 packet's (like: `"receiver": "xyz"`).  If that's what this code does, then I'm happy with it!

**Review by romac — APPROVED** [review]

**Pull request merged**
