### PR TITLE
fix: calculate trace hash from both class ID and token ID

### PR DESCRIPTION
**Pull request by yito88**
## Description
Fix for `feat/ics721-impl`

The class ID and the token ID specify the NFT.
The trace hash should be calculated from both IDs, and we need to submit a trace event per each token.

______

### PR author checklist:
- [ ] Added changelog entry, using [`unclog`](https://github.com/informalsystems/unclog).
- [ ] Added tests.
- [ ] Linked to GitHub issue.
- [ ] Updated code comments and documentation (e.g., `docs/`).
- [ ] Tagged *one* reviewer who will be the one responsible for shepherding this PR.

### Reviewer checklist:

- [ ] Reviewed `Files changed` in the GitHub PR explorer.
- [ ] Manually tested (in case integration/unit/mock tests are absent).

### CODE REVIEW

**Review by Farhad-Shabani — APPROVED** [review]
Does this PR mean that the [same event](https://github.com/bianjieai/nft-transfer/blob/1d33cd905efd41fe75ed9a400a130bccf57b5fe8/keeper/relay.go#L299-L304) within the [bianjieai/nft-transfer](https://github.com/bianjieai/nft-transfer) repo should get fixed as well?

**Comment by Farhad-Shabani** [comment]
Just a nit. To pass the CI we need to place `context`, `handler`, and `module` [modules](https://github.com/cosmos/ibc-rs/blob/e5e8464972c04c21cba9ed8686c6d723c85aa71a/ibc-apps/ics721-nft-transfer/src/lib.rs#L20-L22) under the `#[cfg(feature = "serde")]` flag

**Comment by yito88** [comment]
> Does this PR mean that the [same event](https://github.com/bianjieai/nft-transfer/blob/1d33cd905efd41fe75ed9a400a130bccf57b5fe8/keeper/relay.go#L299-L304) within the [bianjieai/nft-transfer](https://github.com/bianjieai/nft-transfer) repo should get fixed as well?

I think so. In `bianjieai/nft-transfer`, the prefixed class is handled like the prefixed denom in ICS-20. However, specifying the actual token is required with not only the class but also the token ID. In Cosmos, a non-NFT token received over IBC is shown as `ibc/{hash}`. I believe it's natural to express both non-NFT and NFT as `ibc/{hash}`.

**Comment by Farhad-Shabani** [comment]
> > Does this PR mean that the [same event](https://github.com/bianjieai/nft-transfer/blob/1d33cd905efd41fe75ed9a400a130bccf57b5fe8/keeper/relay.go#L299-L304) within the [bianjieai/nft-transfer](https://github.com/bianjieai/nft-transfer) repo should get fixed as well?
> 
> I think so. In `bianjieai/nft-transfer`, the prefixed class is handled like the prefixed denom in ICS-20. However, specifying the actual token is required with not only the class but also the token ID. In Cosmos, a non-NFT token received over IBC is shown as `ibc/{hash}`. I believe it's natural to express both non-NFT and NFT as `ibc/{hash}`.

Makes sense. Thank you!

**Pull request merged**
