### PR TITLE
upgrade_client: Make `TYPE_URL` public

### PR DESCRIPTION
**Pull request by kevinji**
Closes: #XXX

## Description

This makes `upgrade_client::TYPE_URL` public to match the visibility of all other `TYPE_URL` constants, and makes it easier to access outside of the crate.

______

### PR author checklist:
- [x] Added changelog entry, using [`unclog`](https://github.com/informalsystems/unclog).
- [ ] Added tests.
- [ ] Linked to GitHub issue.
- [ ] Updated code comments and documentation (e.g., `docs/`).
- [ ] Tagged *one* reviewer who will be the one responsible for shepherding this PR.

### Reviewer checklist:

- [ ] Reviewed `Files changed` in the GitHub PR explorer.
- [ ] Manually tested (in case integration/unit/mock tests are absent).

### CODE REVIEW

**Comment by Farhad-Shabani** [comment]
Thanks for pointing out this discrepancy.

Considering the existing [`type_url`](https://github.com/cosmos/ibc-rs/blob/060d80fc66c1de1a82c64ac193f7329ed3f2d326/crates/ibc/src/tx_msg.rs#L8) interface for each message type, it sounds like we should take the opposite approach and make others `pub(crate)` to improve encapsulation and prevents confusion for callers, as some use `type_url()` and others might import `TYPE_URL` const.

Based on a [previous](https://github.com/cosmos/ibc-rs/pull/315) review, it appears that `TYPE_URL` is typically used for converting a domain message to `Any`, which accepts a `String` type. For this usage as well, calling the `type_url()` method is better.

**Comment by plafer** [comment]
@kevinji do you have a use case for needing the `TYPE_URL`? As Farhad mentioned, we were instead going to move in the direction of making all the other `TYPE_URL` private.

**Comment by kevinji** [comment]
Nope I didn't know that `tx_msg::Msg` existed, so closing in favor of using that interface.

**Comment by Farhad-Shabani** [comment]
> Nope I didn't know that `tx_msg::Msg` existed, so closing in favor of using that interface.

👍🏻 
by the way, I opened #597 to deal with it at the appropriate time

**Comment by plafer** [comment]
> Nope I didn't know that tx_msg::Msg existed, so closing in favor of using that interface.

Could you link to an example snippet where you need the `TYPE_URL` or `tx_msg::Msg::type_url`? I was hoping to get rid of `tx_msg::Msg` too.

**Comment by kevinji** [comment]
It's essentially the same use case as #586 as I'm currently directly using `MsgEnvelope` in one of my types:

```rust
                match msg_envelope {
                    // ICS2 messages
                    MsgEnvelope::Client(ClientMsg::CreateClient(domain_msg)) => domain_msg.to_any(),
                    MsgEnvelope::Client(ClientMsg::UpdateClient(domain_msg)) => domain_msg.to_any(),
                    MsgEnvelope::Client(ClientMsg::UpgradeClient(domain_msg)) => {
                        domain_msg.to_any()
                    }
                    // ...
                }
```

I do plan to switch these to be backed by the raw types instead, per the discussions we've had, but for now I'm using `tx_msg::Msg` to help with serialization.

**Pull request closed without merging**
