### PR TITLE
Implemented GRPC client to query account sequence

### PR DESCRIPTION
**Pull request by andynog**
Closes: #337

## Description

This PR has the logic to start using the GRPC service from a Cosmos chain to retrieve account information. The account has the sequence number that is needed to submit a transaction. With this implementation there is no need anymore to manually query the account sequence in order to submit a transaction. Changes implemented:

* Added logic to proto_compiler to generate the GRPC client (using [tonic](https://github.com/hyperium/tonic)
* Added logic to retrieve the GRPC address from the configuration file
* Added method to Cosmos chain to query_account that leverages the GRPC client
* Removed the old account sequence parameter from the `tx raw` command
* Updated instructions on Relayer CLI README to remove the account sequence instructions

______

For contributor use:

- [ ] Updated the __Unreleased__ section of [CHANGELOG.md](https://github.com/informalsystems/ibc-rs/blob/master/CHANGELOG.md) with the issue.
- [ ] If applicable: Unit tests written, added test to CI.
- [X] Linked to Github issue with discussion and accepted design OR link to spec that describes this work.
- [X] Updated relevant documentation (`docs/`) and code comments.
- [ ] Re-reviewed `Files changed` in the Github PR explorer.

### CODE REVIEW

**Comment by andynog** [comment]
Just noticed there a lot of file changes but a lot of them are proto files that were updated and after including tonic seems it also formatted the files.

**Comment by andynog** [comment]
There might be an additional change required which is the cosmos address from the key_seed.json. Right now it has a hard coded address. I will look into this tomorrow.

**Review by romac — COMMENTED** [review]
LGTM but will defer to @ancazamfir for the final approbation. Great stuff @andynog!

**Review by ancazamfir — COMMENTED** [review]
Looks good! Thanks Andy!! 
Please update the changelog and pin the protos to sdk `v0.40.0-rc0` (commit 15324920548c2629e51d837bcefc1cbc40797c5d)

**Comment by andynog** [comment]
@ancazamfir, I've merged #365 and there were a lot of merging conflicts that I've resolved to the best of my knowledge. Since there were not only changes related to the proto compiler but also for the tx commands maybe from other commits to master, I had to resolve these conflicts. The only weird thing is that if I run a `conn-init` tx like I've been testing, using the `dev-env` I cannot see the connection created and the output of the command is `Success client updated: [ ]`. So not sure something changed or it's something wrong with the merging.

Could you please test the txs with this branch and see if still makes sense for you ?

Here's what I've tested
```
cargo run --bin relayer -- -c ./relayer-cli/tests/fixtures/two_chains.toml tx raw conn-init ibc0 ibc1 ibczeroclient ibconeclient ibczeroconn246 -k key
_seed.json
```

and I get

```
 Finished dev [unoptimized + debuginfo] target(s) in 0.13s
     Running `target/debug/relayer -c ./relayer-cli/tests/fixtures/two_chains.toml tx raw conn-init ibc0 ibc1 ibczeroclient ibconeclient ibczeroconn246 -k key_seed.json`
     Message ConnectionOpenInitOptions { dest_chain_config: ChainConfig { id: chain::Id(ibc0), rpc_addr: Tcp { peer_id: None, host: "localhost", port: 26657 }, grpc_addr: "tcp://localhost:9090", account_prefix: "cosmos", key_name: "testkey", store_prefix: "ibc", client_ids: ["cla1", "cla2"], gas: 200000, clock_drift: 5s, trusting_period: 1209600s, trust_threshold: TrustThresholdFraction { numerator: 1, denominator: 3 }, peers: Some(PeersConfig { primary: node::Id(E0DE6C540C65FC9059660A7A8535F70048A94539), light_clients: [LightClientConfig { peer_id: node::Id(E0DE6C540C65FC9059660A7A8535F70048A94539), address: Tcp { peer_id: None, host: "localhost", port: 26657 }, trusted_header_hash: Hash::Sha256(169F8F6318B8FAABDBA128AD1689E238566B69DDBD2B36F1911C0DFCA73FD401), trusted_height: block::Height(7806) }] }) }, src_chain_config: ChainConfig { id: chain::Id(ibc1), rpc_addr: Tcp { peer_id: None, host: "localhost", port: 26557 }, grpc_addr: "tcp://localhost:9091", account_prefix: "cosmos", key_name: "testkey", store_prefix: "ibc", client_ids: ["clb1"], gas: 200000, clock_drift: 5s, trusting_period: 1209600s, trust_threshold: TrustThresholdFraction { numerator: 1, denominator: 3 }, peers: Some(PeersConfig { primary: node::Id(356DB878F398BA707DBE69950067C8E6471D8948), light_clients: [LightClientConfig { peer_id: node::Id(356DB878F398BA707DBE69950067C8E6471D8948), address: Tcp { peer_id: None, host: "localhost", port: 26557 }, trusted_header_hash: Hash::Sha256(CC291E79B2E2068984EB13BBF420B4F4AE95357E25B9BA0A30CA26FF27AF3C75), trusted_height: block::Height(7741) }] }) }, dest_client_id: ClientId("ibczeroclient"), src_client_id: ClientId("ibconeclient"), dest_connection_id: ConnectionId("ibczeroconn246"), src_connection_id: None, signer_seed: "{\"name\":\"user\",\"type\":\"local\",\"address\":\"cosmos1x09nchne8s9wya2nwl0erhmf4qz4uhwkx2gyu9\",\"pubkey\":\"cosmospub1addwnpepqf029w068elsesh3s35chgze5m4exvkmrqjrrgakav85c7y4sl0aq4727f3\",\"mnemonic\":\"[MNEMONIC]t\"}\n" }
     Success client updated: []
```

**Review by ancazamfir — APPROVED** [review]
Looks great! Thanks Andy!

**Pull request merged**
