### PR TITLE
chore: update some dependencies

### PR DESCRIPTION
**Pull request by Farhad-Shabani**
Closes: #XXX

__

### PR author checklist:
- [ ] Added changelog entry, using [`unclog`](https://github.com/informalsystems/unclog).
- [ ] Added tests.
- [ ] Linked to GitHub issue.
- [ ] Updated code comments and documentation (e.g., `docs/`).
- [ ] Tagged *one* reviewer who will be the one responsible for shepherding this PR.

### Reviewer checklist:

- [ ] Reviewed `Files changed` in the GitHub PR explorer.
- [ ] Manually tested (in case integration/unit/mock tests are absent).

### CODE REVIEW

**Comment by rnbguy** [comment]
@Farhad-Shabani, I maybe out of context. So let me ask few questions.

0. Is this a standard `cargo upgrade` PR?
1. Can you please explain why the `time` crate dependency looks like this?

**Comment by Farhad-Shabani** [comment]
> 0. Is this a standard `cargo upgrade` PR?

Yes, I just gathered several into one PR

> 1. Can you please explain why the `time` crate dependency looks like this?

My understanding, dependent projects might be on a different exact version of `time`. By using a version range, we allow updates without forcing projects to upgrade, especially, like here, when only the patch numbers have changed.

**Comment by rnbguy** [comment]
~Can't we directly use `0.3` in that case?~

Ah please ignore my previous reply. I was under the impression that `0.3` is equivalent to `>=0.3.0, <0.4.0`.

But, according to [cargo doc](https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html), it's actually equivalent to `>=0.3.0, <1.0.0`.

**Comment by rnbguy** [comment]
Just realized, I was suggesting ~0.3 or 0.3.* (equivalent to >=0.3.0, <0.4.0).

Does it work here?

**Comment by Farhad-Shabani** [comment]
> Just realized, I was suggesting ~0.3 or 0.3.* (equivalent to >=0.3.0, <0.4.0).
> 
> Does it work here?

Yes. Both works, though with a bit differences. 
IMO, the current one provides more information. At a glance, users can see the exact support range. Besides, makes us to review patches (though usually it's a quick one), allowing us to stay informed and support only up to the version we reviewed.

**Review by rnbguy — APPROVED** [review]
Explanations looks good. Thanks Farhad !

**Pull request merged**
