### PR TITLE
Cleanup access to state handler

### PR DESCRIPTION
**Pull request by Wizdave97**
Closes: https://github.com/informalsystems/ibc-rs/issues/631

## Description

Remove getters from  client, connection and channel messages
______

### PR author checklist:
- [ ] Added changelog entry, using [`unclog`](https://github.com/informalsystems/unclog).
- [ ] Added tests: integration (for Hermes) or unit/mock tests (for modules). 
- [ ] Linked to GitHub issue.
- [ ] Updated code comments and documentation (e.g., `docs/`).

### Reviewer checklist:

- [ ] Reviewed `Files changed` in the GitHub PR explorer.
- [ ] Manually tested (in case integration/unit/mock tests are absent).

### CODE REVIEW

**Review by romac — APPROVED** [review]
Very nice, thanks a lot!

**Comment by romac** [comment]
@Wizdave97 Can you please either fix the two remaining warnings by applying this patch, or [allow edits by maintainers](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork) for this PR?

```diff
diff --git a/modules/src/core/ics03_connection/handler/conn_open_confirm.rs b/modules/src/core/ics03_connection/handler/conn_open_confirm.rs
index b32605be..a2849217 100644
--- a/modules/src/core/ics03_connection/handler/conn_open_confirm.rs
+++ b/modules/src/core/ics03_connection/handler/conn_open_confirm.rs
@@ -141,7 +141,7 @@ mod tests {
                 ctx: context
                     .with_client(&client_id, Height::new(0, 10))
                     .with_connection(msg_confirm.connection_id.clone(), correct_conn_end),
-                msg: ConnectionMsg::ConnectionOpenConfirm(msg_confirm.clone()),
+                msg: ConnectionMsg::ConnectionOpenConfirm(msg_confirm),
                 want_pass: true,
             },
         ]
diff --git a/modules/src/core/ics04_channel/handler/chan_open_init.rs b/modules/src/core/ics04_channel/handler/chan_open_init.rs
index 81a01760..d37edc6d 100644
--- a/modules/src/core/ics04_channel/handler/chan_open_init.rs
+++ b/modules/src/core/ics04_channel/handler/chan_open_init.rs
@@ -146,8 +146,7 @@ mod tests {
                     .with_port_capability(
                         MsgChannelOpenInit::try_from(get_dummy_raw_msg_chan_open_init())
                             .unwrap()
-                            .port_id
-                            .clone(),
+                            .port_id,
                     ),
                 msg: ChannelMsg::ChannelOpenInit(msg_chan_init),
                 want_pass: true,
```

**Review by romac — APPROVED** [review]
Thanks so much, @Wizdave97!

**Comment by Wizdave97** [comment]
> Thanks so much, @Wizdave97!

My pleasure, @romac  is there like an active platform where the contributors to this project meet and discuss technical details of the project, I would like to work on more technical tasks, but I my understanding is still limited, If there is a platform I'd love to join.

**Pull request merged**
