### PR TITLE
Model based testing on integration tests

### PR DESCRIPTION
**Pull request by rnbguy**
Closes: #2070

## Description

This PR contains the sources to enable Model Based Testing (MBT) in the integration test framework.

It extends two integration tests using MBT.
- Successful token transfer
- Unsuccessful token transfer (in case of IBC packet expiration)

### Instructions
- [TLA+ specifications](https://github.com/informalsystems/ibc-rs/blob/rnbguy/integration-test/mbt/tools/integration-test/spec/README.md)
- [Rust MBT](https://github.com/informalsystems/ibc-rs/blob/rnbguy/integration-test/mbt/tools/integration-test/src/mbt/README.md) 

Next action items,
- [x] Create a CI for MBT tests.
- [x] Add/Refer instructions to setup `apalache` as dependency.
- [ ] Describe the link between TLA+ specifications and Rust code.
- [x] Instructions on running `apalache` on the specifications manually.
- [x] Maintain example traces from `apalache` for manual inspection.

______

### PR author checklist:
- [ ] Added changelog entry, using [`unclog`](https://github.com/informalsystems/unclog).
- [x] Added tests: integration (for Hermes) or unit/mock tests (for modules). 
- [x] Linked to GitHub issue.
- [ ] Updated code comments and documentation (e.g., `docs/`).

### Reviewer checklist:

- [ ] Reviewed `Files changed` in the GitHub PR explorer.
- [ ] Manually tested (in case integration/unit/mock tests are absent).

### CODE REVIEW

**Comment by romac** [comment]
Wow, amazing work @rnbguy! 🎉 🙌

**Comment by adizere** [comment]
After sync-ing with the team:

> Rano: Estimate there may be another week of work necessary to get it ready for review. The failing tests are due to Apalache most likely, fixable.
>   - it's important to note that the code here (modelator-side) will become obsolete once the more stable version of modelator comes out (v1).
>  - the TLA+ specs still valuable

> Adi: Sean Chen, maybe consider familiarizing yourself with the TLA+ specs. We don't expect these will need maintenance, but it's good to have a person who understands that front. This should not block merging, however.

> Soares: The two important requiremets are: (1) save traces both on failure & succcess, and (2) get the CI tests to pass (related to Apalache error most likely).
>    - worst case, in case we merge this and it will block us in the future, we can consider feature-flagging the MBT tests or disabling them (unless we actually uncover a bug in the relayer)

**Comment by rnbguy** [comment]
@adizere thanks for the summary ! :+1:

I seem to fix the flaky tests. Ran some longer tests, but nothing came up. If everything looks alright, @soareschen and I can close the PR next week :slightly_smiling_face:

**Comment by adizere** [comment]
Wanted to follow-up here and see if the PR is blocked on anything.

The tests are not failing anymore, but a couple of them take too long (~20mins), [specifically the integration test with gaia5 and gaia6](https://github.com/informalsystems/ibc-rs/actions/runs/2281691715). I restarted those jobs to see if they are successful.

**Comment by soareschen** [comment]
Sorry that I forgot to follow up on this PR. It can be merged now.

> The tests are not failing anymore, but a couple of them take too long (~20mins)

We switched the parallel thread for the CI from 2 to 1, and apparently that makes the test run too slow. I have switched it back to run in 2 threads, and the time taken is now the same as master.

**Pull request merged**
