### PR TITLE
Refactor proto-compiler as a proper CLI app

### PR DESCRIPTION
**Pull request by romac**
Closes: #366

## Description

- Refactor the `proto-compiler` crate into a proper CLI app
- Allow specifying the commit of the Cosmos SDK to check out
- Expose the version (commit hash) of the SDK used when generating the `proto` library as a constant.

Screen Shot 2020-11-05 at 19 08 00

### `ibc-proto-compiler`

```
Usage: ibc-proto-compiler <command> [<args>]

App

Options:
  --help            display usage information

Commands:
  clone-sdk         Clone
  compile           Compile
```

### `ibc-proto-compiler clone-sdk`

```
Usage: ibc-proto-compiler clone-sdk [-c <commit>] -o <path>

Clone

Options:
  -c, --commit      commit to checkout
  -o, --path        where to checkout the repository
  --help            display usage information
```

### `ibc-proto-compiler compile`

```
Usage: ibc-proto-compiler compile -s <sdk> -o <out>

Compile

Options:
  -s, --sdk         path to the Cosmos SDK
  -o, --out         path to output the generated Rust sources into
  --help            display usage information
```

______

For contributor use:

- [ ] Updated the __Unreleased__ section of [CHANGELOG.md](https://github.com/informalsystems/ibc-rs/blob/master/CHANGELOG.md) with the issue.
- [ ] If applicable: Unit tests written, added test to CI.
- [ ] Linked to Github issue with discussion and accepted design OR link to spec that describes this work.
- [ ] Updated relevant documentation (`docs/`) and code comments.
- [ ] Re-reviewed `Files changed` in the Github PR explorer.

### CODE REVIEW

**Review by ancazamfir — APPROVED** [review]
Looks great! Thanks Romain!

**Comment by ancazamfir** [comment]
Great UX :) 
It would be nice to also have the `[-t <tag>] option for `clone-sdk` so we can point to tags/ releases. I hope commit hashes become an exception.

**Comment by ancazamfir** [comment]
> Great UX :)
> It would be nice to also have the `[-t <tag>]` option for `clone-sdk` so we can point to tags/ releases. I hope commit hashes become an exception.

Actually, the cosmos-sdk for stargate-4 is at `v0.40.0-rc0`. But we can lookup the commit for now and merge this as this.

**Comment by romac** [comment]
> It would be nice to also have the [-t <tag>] option for clone-sdk so we can point to tags/ releases. I hope commit hashes become an exception.

Agreed! Let's do that in a follow-up PR so that we unblock #361 already.

**Pull request merged**
