### PR TITLE
Add CI job for finding invalid links in markdown files

### PR DESCRIPTION
**Pull request by rnbguy**
Closes: Broken Markdown links

## Description

Adds CI for finding invalid links in markdown files.

______

For contributor use:

- [X] Added a changelog entry, using [`unclog`](https://github.com/informalsystems/unclog).
- [X] If applicable: Unit tests written, added test to CI.
- [X] Linked to Github issue with discussion and accepted design OR link to spec that describes this work.
- [X] Updated relevant documentation (`docs/`) and code comments.
- [X] Re-reviewed `Files changed` in the Github PR explorer.

### CODE REVIEW

**Comment by rnbguy** [comment]
@adizere hey. I created the CI. but it seems, many of the tests failed because Github started sending 429 for too many requests. looks like, I have to create a config file. any idea where I should put it?

ref. https://github.com/marketplace/actions/markdown-link-check#too-many-requests

**Comment by romac** [comment]
I would put it somewhere in the `.github` folder and then use the `config-file` option of the action to point to it (not clear what the path there is relative to though, guess it requires some trial and error).

**Comment by adizere** [comment]
> @adizere hey. I created the CI. but it seems, many of the tests failed because Github started sending 429 for too many requests. looks like, I have to create a config file. any idea where I should put it?
> 
> ref. https://github.com/marketplace/actions/markdown-link-check#too-many-requests

Many thanks Rano!

+1 for [Romain's suggestion](https://github.com/informalsystems/ibc-rs/pull/1244#issuecomment-888923096)! I took the liberty to try and see if it works with the config file (8ee6d44), but seems there are still failures. Weird enough the failures appear for crates.io website (which works).

Not sure how to fix it, a debugging ideas would be to use the [variables](https://github.com/marketplace/actions/markdown-link-check#too-many-requests):        

```
        use-quiet-mode: 'yes'
        use-verbose-mode: 'yes'
```

**Comment by rnbguy** [comment]
Yeah I noticed that about crates.io in first commit too. They are probably blocking the requests too. Add an [`ignorePatterns`](https://github.com/tcort/markdown-link-check#config-file-format) for crates.io.

**Comment by rnbguy** [comment]
The CI is in better shape now. The errors seem to be genuine. I fixed some of them. Currently, there are 3 links that are failing.

**Review by adizere — APPROVED** [review]
This was very helpful, cool work Rano!

**Pull request merged**
