### PR TITLE
decouple proto and grpc 

### PR DESCRIPTION
**Pull request by DaviRain-Su**
relate issue : https://github.com/informalsystems/ibc-rs/issues/1238

______

For contributor use:

- [ ] Added a changelog entry, using [`unclog`](https://github.com/informalsystems/unclog).
- [ ] If applicable: Unit tests written, added test to CI.
- [ ] Linked to Github issue with discussion and accepted design OR link to spec that describes this work.
- [ ] Updated relevant documentation (`docs/`) and code comments.
- [ ] Re-reviewed `Files changed` in the Github PR explorer.

### CODE REVIEW

**Comment by romac** [comment]
Thanks for this PR, splitting the two crates makes sense to me!

Is this the result of manual work? If so, we need to figure out a way to do this programmatically in the [`proto-compiler`](https://github.com/informalsystems/ibc-rs/tree/master/proto-compiler) tool that is part of this repo, and which we use to generate these Rust Protobuf definitions.

**Comment by romac** [comment]
@soareschen What's your take on this? Would you rather bundle the gRPC code in `ibc-proto` or does having two crates make sense to you?

**Comment by DaviRain-Su** [comment]
> Is this the result of manual work?

It's not particularly clear what the proto-compiler does? It seems that the rpc in proto is also written out manually.

**Comment by romac** [comment]
> It seems that the rpc in proto is also written out manually.

It's not. 

> It's not particularly clear what the proto-compiler does? 

`proto-compiler` is a command-line tool we use to generate the Rust code from the Protobuf definitions. The tool can pull the Cosmos SDK and the IBC Go repositories at a specific commit, and will then uses Prost and Tonic to generate the Rust code from the .proto files bundled in the Cosmos SDK/IBC Go repositories. You can check out the README for how to use it.

**Comment by DaviRain-Su** [comment]
> proto-compiler is a command-line tool we use to generate the Rust code from the Protobuf definitions. The tool can pull the Cosmos SDK and the IBC Go repositories at a specific commit, and will then uses Prost and Tonic to generate the Rust code from the .proto files bundled in the Cosmos SDK/IBC Go repositories. You can check out the README for how to use it.

Which is very good, then here you can learn to split proto with rpc with tendermint-rs.

**Comment by soareschen** [comment]
I think it is beneficial to separate the code into two module namespaces or crates. Though this will depend on how well we can generate the code separately. I am looking at the documentation of `prost_build` and `tonic_build` to see if we can invoke the two code generations separately.

**Comment by romac** [comment]
Closing this PR until we manage to generate two separate crates with our `proto-compiler` tool.

**Pull request closed without merging**
