### PR TITLE
`max_expected_time_per_block` in `ChannelReader` returns `Result`

### PR DESCRIPTION
**Pull request by yito88**
Closes: #1864

## Description
`max_expected_time_per_block` and `block_delay` return `Result`

______

### PR author checklist:
- [x] Added changelog entry, using [`unclog`](https://github.com/informalsystems/unclog).
- [x] Added tests: integration (for Hermes) or unit/mock tests (for modules). 
- [x] Linked to GitHub issue.
- [x] Updated code comments and documentation (e.g., `docs/`).

### Reviewer checklist:

- [ ] Reviewed `Files changed` in the GitHub PR explorer.
- [ ] Manually tested (in case integration/unit/mock tests are absent).

### CODE REVIEW

**Comment by romac** [comment]
Thanks @yito88, can you explain the rationale behind this change?

**Comment by romac** [comment]
@hu55a1n1 How would you suggest we proceed here?

**Comment by hu55a1n1** [comment]
@yito88 [previously said](https://github.com/informalsystems/ibc-rs/issues/1864#issuecomment-1035856352) that it is possible for them to use default values -> 
> It happens in our case where the parameter is stored into the persistent storage and the read failed due to IO failure.
> It's possible to return a default value.

AFAIK, IBC doesn't require this parameter to be stored on persistent storage as it is immutable/constant and doesn't need to be proven. 
If it is possible for @yito88 to somehow hard-code this parameter, use defaults or load it in memory on program startup, then I would suggest we leave things as they are.

**Comment by romac** [comment]
> AFAIK, IBC doesn't require this parameter to be stored on persistent storage as it is immutable/constant and doesn't need to be proven.
> If it is possible for @yito88 to somehow hard-code this parameter, use defaults or load it in memory on program startup, then I would suggest we leave things as they are.

@yito88 Does @hu55a1n1's suggestion above make sense to you?

**Comment by yito88** [comment]
Thank you for your explanation. It makes sense.

**Pull request closed without merging**
