### PR TITLE
Enable code formatter when generating protobuf definitions using tonic_build

### PR DESCRIPTION
**Pull request by soareschen**
## Description

Update: This PR enables the code formatter option in `tonic_build` when generating protobuf definitions in `proto-compiler`.

~~I run the following `rustfmt` command on `proto/src/prost` to make it easier to read the generated protobuf definitions:~~

```
rustfmt --edition 2018 --config-path .rustfmt.toml proto/src/prost/*.rs
```

______

For contributor use:

- [ ] Updated the __Unreleased__ section of [CHANGELOG.md](https://github.com/informalsystems/ibc-rs/blob/master/CHANGELOG.md) with the issue.
- [ ] If applicable: Unit tests written, added test to CI.
- [ ] Linked to Github issue with discussion and accepted design OR link to spec that describes this work.
- [ ] Updated relevant documentation (`docs/`) and code comments.
- [ ] Re-reviewed `Files changed` in the Github PR explorer.

### CODE REVIEW

**Review by adizere — COMMENTED** [review]
I have a slight preference for formatting these files at generation time, by passing option `.format(true)` to tonic_build. You can see an example here, if you want to adapt to this approach:
https://github.com/informalsystems/ibc-rs/commit/28445b56828d20d75dac7176f1862bd1f8b6d496#diff-99cd9319d3522f0d529e87ae6e3f9a796273e253a008be20fe34d41a81b3c715R108

(This will make it simpler to maintain the files consistently, as we would only need to be aware of a single step i.e., the `compile` command of proto-compiler, instead of two steps `compile` + `rustfmt`).

**Comment by soareschen** [comment]
Ah good to know that tonic supports generating formatted code. So is your branch being merged already?

**Comment by adizere** [comment]
> Ah good to know that tonic supports generating formatted code. So is your branch being merged already?

I de-prioritized the work on that branch, so it will probably take me 1-2 weeks until I get back to that PR. (The important part of that PR is actually the [generation of server-side code](https://github.com/informalsystems/ibc-rs/commit/77e1c9063236e54f053831e7eb6f0ef25ad7e143), but formatting the code is very nice to have.) If you think it would be useful to have the formatted protobuf files before that, let's go ahead with this PR (but using the tonic-based approach); but if you think this can wait a bit, then I'd suggest we close this PR and leave it for later. I leave it up to you.

**Comment by soareschen** [comment]
Ok then. Since this is relatively trivial I can enable formatting first. I have re-generate the code using `proto-compiler` with formatter turned on. Main notable changes are that `tonic_build` seems to generate struct definitions first when formatting is turned on.

**Comment by adizere** [comment]
Great, thanks Soares!

One more thing: it would be nice to have an issue describing briefly what this PR will close (even if it's a minor change) + add changelog entry, and update the PR description.

**Comment by soareschen** [comment]
Sure, updated.

**Review by adizere — APPROVED** [review]

**Pull request merged**
