### PR TITLE
MBT: Use modelator crate

### PR DESCRIPTION
**Pull request by vitorenesduarte**
Closes: #761 

## Description

With this PR, we start using [`modelator`](https://github.com/informalsystems/modelator), a model-based testing tool being developed at Informal. In particular:
- the following files were removed as their functionality is now provided by `modelator`:
  - `modules/tests/executor/modelator.rs`
  - `modules/tests/support/model_based/gen_tests.py`
- all static files in `modules/tests/support/model_based/tests/` representing the tests generated by the model checkers are now generated on the fly (there are plans to cache them (see https://github.com/informalsystems/modelator/issues/27), which will speed up the developer experience when using `modelator`, but it won't improve CI times)

This PR currently relies on an unreleased version of `modelator`. This will be fixed by a follow-up PR (containing other improvements) once we do a proper release of `modelator` later this week.

______

For contributor use:

- [ ] Updated the __Unreleased__ section of [CHANGELOG.md](https://github.com/informalsystems/ibc-rs/blob/master/CHANGELOG.md) with the issue.
- [ ] If applicable: Unit tests written, added test to CI.
- [ ] Linked to Github issue with discussion and accepted design OR link to spec that describes this work.
- [ ] Updated relevant documentation (`docs/`) and code comments.
- [ ] Re-reviewed `Files changed` in the Github PR explorer.

### CODE REVIEW

**Review by romac — APPROVED** [review]
Awesome 🎉

**Comment by romac** [comment]
@vitorenesduarte Can you please update the changelog before we merge?

**Comment by vitorenesduarte** [comment]
> @vitorenesduarte Can you please update the changelog before we merge?

@romac Not sure it's a requirement for this kind of PRs, but I opened an issue and linked it in the changelog. Please check if this is okay.

**Comment by romac** [comment]
Perfect, thanks!

**Pull request merged**
