### PR TITLE
Unambiguous packet query

### PR DESCRIPTION
**Pull request by vitorenesduarte**
Closes: #614

## Description

Before, a `query_txs` for a packet on a given chain would filter only by the packet source port, source channel and sequence.
With 2 chains, there can be at most a single packet matching such filter, and this fact was assumed in the code.

However, this assumption does not hold with more than 2 chains. To understand why, consider the following example with chains `ibc-0`, `ibc-1` and `ibc-2`:
- a channel handshake occurs between `ibc-0` and `ibc-1`; the channel identifiers are `channel-0` on both ends
- a channel handshake occurs between `ibc-1` and `ibc-2`; the channel identifier on `ibc-1` is `channel-1` and on `ibc-2` is `channel-0`

If now both `ibc-0` and `ibc-2` send packets to `ibc-1` and we do a packet query filtering only by the source, such query will return
packets from both `ibc-0` and `ibc-1` (as both have `channel-0` as the source channel in their packets).

In this commit, we start filtering also by the destination port and destination channel. This makes the packet query unambiguous.

Thanks @ancazamfir for the help debugging this issue. It was a fun one!

______

For contributor use:

- [ ] Updated the __Unreleased__ section of [CHANGELOG.md](https://github.com/informalsystems/ibc-rs/blob/master/CHANGELOG.md) with the issue.
- [ ] If applicable: Unit tests written, added test to CI.
- [ ] Linked to Github issue with discussion and accepted design OR link to spec that describes this work.
- [ ] Updated relevant documentation (`docs/`) and code comments.
- [ ] Re-reviewed `Files changed` in the Github PR explorer.

### CODE REVIEW

**Comment by vitorenesduarte** [comment]
> With 2 chains, there can be at most a single packet matching such filter, and this fact was assumed in the code.

I left a TODO to make this assumption explicit. It will be addressed in a following PR.

**Review by ancazamfir — APPROVED** [review]
Looks good! Thanks again!

**Comment by romac** [comment]
@vitorenesduarte Awesome, thanks! Could you please create an issue and open a PR to add a changelog entry for this, mentioning said issue?

**Comment by romac** [comment]
^ This can be done as part of your follow-up PR.

**Comment by vitorenesduarte** [comment]
> @vitorenesduarte Awesome, thanks! Could you please create an issue and open a PR to add a changelog entry for this, mentioning said issue?

Oh, right 😅 @romac Here it goes: https://github.com/informalsystems/ibc-rs/pull/617

**Pull request merged**
