### PR TITLE
Full support of no_std in `ibc` crate

### PR DESCRIPTION
**Pull request by soareschen**
Part of #1158

## Description

~This PR currently uses the branch at informalsystems/tendermint-rs#988 to get rid of the dependency to `std::time::SystemTime`. Once that is merged, we can merge this for no_std support on the `ibc` itself.~

~Note that as mentioned in #1158, even though the `ibc` crate itself now supports no_std, some of its dependencies including tendermint-rs still depend on `std`.~

Update: The PR now fully supports no_std in the `ibc` crate.

______

For contributor use:

- [ ] Added a changelog entry, using [`unclog`](https://github.com/informalsystems/unclog).
- [ ] If applicable: Unit tests written, added test to CI.
- [ ] Linked to Github issue with discussion and accepted design OR link to spec that describes this work.
- [ ] Updated relevant documentation (`docs/`) and code comments.
- [ ] Re-reviewed `Files changed` in the Github PR explorer.

### CODE REVIEW

**Comment by soareschen** [comment]
We will wait for the other 2 PRs to be merged first, since changes are still being made there.

**Comment by soareschen** [comment]
This PR now also merges from #1395.

**Comment by soareschen** [comment]
The no-std-check scripts on this branch is finally passing. With this we should have finally managed to remove every single use of `std` from the `ibc` crate and all its transitive dependencies.

@DaviRain-Su can you check if this is indeed the case by building it on Substrate?

This is quite a substantial PR, with many pending sub-PRs to be merged first. I cannot guarantee when we will merge this to master and publish the changes, as I also have other high priority tasks to work on. Until then @DaviRain-Su is it fine if you do your development based on this branch?

**Comment by DaviRain-Su** [comment]
> The no-std-check scripts on this branch is finally passing. With this we should have finally managed to remove every single use of `std` from the `ibc` crate and all its transitive dependencies.
> 
> @DaviRain-Su can you check if this is indeed the case by building it on Substrate?
> 
> This is quite a substantial PR, with many pending sub-PRs to be merged first. I cannot guarantee when we will merge this to master and publish the changes, as I also have other high priority tasks to work on. Until then @DaviRain-Su is it fine if you do your development based on this branch?

## FIND QUESTION

I ran into some problems testing this branch, just testing that it hadn't been merged with my code.

## This is `cargo check -p some-crate` to test support std

1. Test case: `cargo check -p ibc-relayer`
```
error[E0277]: the trait bound `DecodeError: StdError` is not satisfied
   --> modules/src/ics26_routing/error.rs:9:1
    |
9   | / define_error! {
10  | |     #[derive(Debug, PartialEq, Eq)]
11  | |     Error {
12  | |         Ics02Client
...   |
35  | |     }
36  | | }
    | |_^ the trait `StdError` is not implemented for `DecodeError`
    |
    = note: required because of the requirements on the impl of `ErrorTracer<DecodeError>` for `eyre::Report`
    = note: required because of the requirements on the impl of `ErrorSource<eyre::Report>` for `TraceError<DecodeError>`
note: required because it appears within the type `ics02_client::error::ErrorDetail`
   --> modules/src/ics02_client/error.rs:14:1
    |
14  | / define_error! {
15  | |     #[derive(Debug, PartialEq, Eq)]
16  | |     Error {
17  | |         UnknownClientType
...   |
212 | |     }
213 | | }
    | |_^
note: required because it appears within the type `ics26_routing::error::ErrorDetail`
   --> modules/src/ics26_routing/error.rs:9:1
    |
9   | / define_error! {
10  | |     #[derive(Debug, PartialEq, Eq)]
11  | |     Error {
12  | |         Ics02Client
...   |
35  | |     }
36  | | }
    | |_^
    = note: only the last element of a tuple may have a dynamically sized type
    = note: this error originates in the macro `$crate::define_main_error` (in Nightly builds, run with -Z macro-backtrace for more info)

```

2. Test Case: `cargo check -p ibc-relayer` 
```
error[E0432]: unresolved import `crossbeam_channel::Sender`
 --> relayer/src/config/reload.rs:6:5
  |
6 | use crossbeam_channel::Sender;
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^ no `Sender` in the root

error[E0432]: unresolved import `crossbeam_channel::TryRecvError`
 --> relayer/src/rest.rs:1:5
  |
1 | use crossbeam_channel::TryRecvError;
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ no `TryRecvError` in the root

error[E0432]: unresolved imports `crossbeam_channel::Receiver`, `crossbeam_channel::Sender`
 --> relayer/src/supervisor.rs:7:25
  |
7 | use crossbeam_channel::{Receiver, Sender};
  |                         ^^^^^^^^  ^^^^^^ no `Sender` in the root
  |                         |
  |                         no `Receiver` in the root

error[E0432]: unresolved import `crossbeam_channel::Sender`
 --> relayer/src/supervisor/cmd.rs:1:5
  |
1 | use crossbeam_channel::Sender;
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^ no `Sender` in the root

error[E0432]: unresolved imports `crossbeam_channel::Receiver`, `crossbeam_channel::Select`
 --> relayer/src/util/recv_multiple.rs:1:25
  |
1 | use crossbeam_channel::{Receiver, Select};
  |                         ^^^^^^^^  ^^^^^^ no `Select` in the root
  |                         |
  |                         no `Receiver` in the root
```
3. Test Case: `cargo check -p ibc-telemetry`
```
error[E0277]: the trait bound `DecodeError: StdError` is not satisfied
   --> modules/src/ics26_routing/error.rs:9:1
    |
9   | / define_error! {
10  | |     #[derive(Debug, PartialEq, Eq)]
11  | |     Error {
12  | |         Ics02Client
...   |
35  | |     }
36  | | }
    | |_^ the trait `StdError` is not implemented for `DecodeError`
    |
    = note: required because of the requirements on the impl of `ErrorTracer<DecodeError>` for `eyre::Report`
    = note: required because of the requirements on the impl of `ErrorSource<eyre::Report>` for `TraceError<DecodeError>`
note: required because it appears within the type `ics02_client::error::ErrorDetail`
   --> modules/src/ics02_client/error.rs:14:1
    |
14  | / define_error! {
15  | |     #[derive(Debug, PartialEq, Eq)]
16  | |     Error {
17  | |         UnknownClientType
...   |
212 | |     }
213 | | }
    | |_^
note: required because it appears within the type `ics26_routing::error::ErrorDetail`
   --> modules/src/ics26_routing/error.rs:9:1
    |
9   | / define_error! {
10  | |     #[derive(Debug, PartialEq, Eq)]
11  | |     Error {
12  | |         Ics02Client
...   |
35  | |     }
36  | | }
    | |_^
    = note: only the last element of a tuple may have a dynamically sized type
    = note: this error originates in the macro `$crate::define_main_error` (in Nightly builds, run with -Z macro-backtrace for more info)

```
4. Test Case: `cargo check -p ibc-relayer-cli` 
   SUCCESS
5. Test Case: `cargo check -p ibc-relayer-rest`
   SUCCESS
6.  Test Case: `cargo check -p ibc-proto`
   SUCCESS

## This is `cargo check -p some-crate --no-default-featurtes` to test support no_std

1. Test Case: `cargo check -p ibc --no-default-features`
   SUCCESS
2. Test Case: `cargo check -p ibc-relayer --no-default-features`
```
error[E0432]: unresolved import `crossbeam_channel::Sender`
 --> relayer/src/config/reload.rs:6:5
  |
6 | use crossbeam_channel::Sender;
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^ no `Sender` in the root

error[E0432]: unresolved import `crossbeam_channel::TryRecvError`
 --> relayer/src/rest.rs:1:5
  |
1 | use crossbeam_channel::TryRecvError;
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ no `TryRecvError` in the root

error[E0432]: unresolved imports `crossbeam_channel::Receiver`, `crossbeam_channel::Sender`
 --> relayer/src/supervisor.rs:7:25
  |
7 | use crossbeam_channel::{Receiver, Sender};
  |                         ^^^^^^^^  ^^^^^^ no `Sender` in the root
  |                         |
  |                         no `Receiver` in the root

error[E0432]: unresolved import `crossbeam_channel::Sender`
 --> relayer/src/supervisor/cmd.rs:1:5
  |
1 | use crossbeam_channel::Sender;
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^ no `Sender` in the root

error[E0432]: unresolved imports `crossbeam_channel::Receiver`, `crossbeam_channel::Select`
 --> relayer/src/util/recv_multiple.rs:1:25
  |
1 | use crossbeam_channel::{Receiver, Select};
  |                         ^^^^^^^^  ^^^^^^ no `Select` in the root
  |                         |
  |                         no `Receiver` in the root
```
3. Test Case: `cargo check -p ibc-relayer-cli --no-default-features`
   SUCCESS
4. Test Case: `cargo check -p ibc-relayer-rest --no-default-features`
   SUCCESS
5. Test Case: `cargo check -p ibc-telemetry --no-default-features`
```
error[E0277]: the trait bound `DecodeError: StdError` is not satisfied
   --> modules/src/ics26_routing/error.rs:9:1
    |
9   | / define_error! {
10  | |     #[derive(Debug, PartialEq, Eq)]
11  | |     Error {
12  | |         Ics02Client
...   |
35  | |     }
36  | | }
    | |_^ the trait `StdError` is not implemented for `DecodeError`
    |
    = note: required because of the requirements on the impl of `ErrorTracer<DecodeError>` for `eyre::Report`
    = note: required because of the requirements on the impl of `ErrorSource<eyre::Report>` for `TraceError<DecodeError>`
note: required because it appears within the type `ics02_client::error::ErrorDetail`
   --> modules/src/ics02_client/error.rs:14:1
    |
14  | / define_error! {
15  | |     #[derive(Debug, PartialEq, Eq)]
16  | |     Error {
17  | |         UnknownClientType
...   |
212 | |     }
213 | | }
    | |_^
note: required because it appears within the type `ics26_routing::error::ErrorDetail`
   --> modules/src/ics26_routing/error.rs:9:1
    |
9   | / define_error! {
10  | |     #[derive(Debug, PartialEq, Eq)]
11  | |     Error {
12  | |         Ics02Client
...   |
35  | |     }
36  | | }
    | |_^
    = note: only the last element of a tuple may have a dynamically sized type
    = note: this error originates in the macro `$crate::define_main_error` (in Nightly builds, run with -Z macro-backtrace for more info)

```
6. Test Case: `cargo check -p ibc-proto --no-default-features`
   SUCCESS

## SUMMARY

Some of my conclusions, when modifying the features that support no_std, should also keep the original std features is no problem.

**Comment by DaviRain-Su** [comment]
@soareschen Hi, I'm having some problems integrating `ibc-rs` to `substrate-ibc`, can you help take a look at it?

This is occur error:
```
error[E0512]: cannot transmute between types of different sizes, or dependently-sized types
  --> primitives/runtime-interface/src/impls.rs:44:1
   |
44 | assert_eq_size!(usize, u32);
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: source type: `usize` (64 bits)
   = note: target type: `u32` (32 bits)
   = note: this error originates in the macro `assert_eq_size` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0512]: cannot transmute between types of different sizes, or dependently-sized types
  --> primitives/runtime-interface/src/impls.rs:46:1
   |
46 | assert_eq_size!(*const u8, u32);
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: source type: `*const u8` (64 bits)
   = note: target type: `u32` (32 bits)
   = note: this error originates in the macro `assert_eq_size` (in Nightly builds, run with -Z macro-backtrace for more info)

For more information about this error, try `rustc --explain E0512`.
error: could not compile `sp-runtime-interface` due to 2 previous errors
```
Some other issues are that some libraries don't seem to support no-std, but you also added the default-features = false switch. For example: `tendermint-rs` introduces some carate: `async-trait`, `serde_repr`, `zeroize`, `num-derive`, etc., and one is not to write pallet like in substrate to support no-std in `ibc-rs` and `tendermint-rs`. std, here is an article you can look at: https://justjjy.com/Rust-no-std

**Comment by livelybug** [comment]
> The error seems to come from `sp-runtime-interface`, which is not used by `ibc-rs` or `tendermint-rs`. I probably ran into similar issue before, and you might want to check if you are using the latest nightly version of Rust. Otherwise you could try `nightly-2021-09-01` which should compile successfully.

Related issue: https://github.com/paritytech/substrate/issues/10111

**Comment by DaviRain-Su** [comment]
Now, for `substrate-ibc` can  run this command test pass no-std support: `cargo check -p pallet-ibc --no-default-features  --target wasm32-unknown-unknown`

**Comment by soareschen** [comment]
Superceded by #1846.

**Pull request closed without merging**
