### PR TITLE
Show `ERROR` in red when a command fails

### PR DESCRIPTION
**Pull request by AlianBenabdallah**
Closes: https://github.com/informalsystems/ibc-rs/issues/2431

Same PR as https://github.com/informalsystems/ibc-rs/pull/2460 but without commits from another branch

## Description

The output of CLI can be confusing (see linked issue). This PR shows the status of the output in green if the command succeeds or in red if it fails.

______

### PR author checklist:
- [x] Added changelog entry, using [`unclog`](https://github.com/informalsystems/unclog).
- [ ] Added tests: integration (for Hermes) or unit/mock tests (for modules). 
- [x] Linked to GitHub issue.
- [ ] Updated code comments and documentation (e.g., `docs/`).

### Reviewer checklist:

- [ ] Reviewed `Files changed` in the GitHub PR explorer.
- [ ] Manually tested (in case integration/unit/mock tests are absent).

### CODE REVIEW

**Review by adizere — COMMENTED** [review]
Looks good, changelog is all that we need to get this merged. Please have a look here https://github.com/informalsystems/ibc-rs/blob/master/CONTRIBUTING.md#examples

**Comment by romac** [comment]
Before merging, let me just test whether or not the `console` crate deals with piped output where the colors should be disabled.

**Comment by romac** [comment]
All good, colors are properly disabled when the `hermes` output is piped to something that's not a tty (eg. a file or `tee`).

**Comment by romac** [comment]
Just needs a changelog entry and we are good to go

**Comment by AlianBenabdallah** [comment]
> Just needs a changelog entry and we are good to go

Done !

**Review by romac — APPROVED** [review]

**Pull request merged**
