### PR TITLE
Refactor MBT for ICS02 & ICS03 using new modelator Rust API

### PR DESCRIPTION
**Pull request by andrey-kuprianov**
Closes: #713 

## Description

Refactoring of MBT for ICS02 & ICS03 using the new `modelator` Rust API 
______

For contributor use:

- [ ] Updated the __Unreleased__ section of [CHANGELOG.md](https://github.com/informalsystems/ibc-rs/blob/master/CHANGELOG.md) with the issue.
- [ ] If applicable: Unit tests written, added test to CI.
- [ ] Linked to Github issue with discussion and accepted design OR link to spec that describes this work.
- [ ] Updated relevant documentation (`docs/`) and code comments.
- [ ] Re-reviewed `Files changed` in the Github PR explorer.

### CODE REVIEW

**Comment by romac** [comment]
@andrey-kuprianov What's the status on this? Can we expect to merge it sometime or is there much left to do?

**Comment by andrey-kuprianov** [comment]
@romac There is not much to do actually, besides that this depends on the https://github.com/informalsystems/modelator/pull/44 PR being merged, and there are still some bugs preventing this. I will address those in the beginning of the next week.

Sorry for the delay -- there are many other things I need to take care of, unfortunately, so everything progresses a bit slow.

**Comment by romac** [comment]
Thanks for the update! I didn't want to imply there was a rush of any kind, just wanted to enquire about the status as I'd like to see that work being put to use for the sake of Hermes :)

**Comment by andrey-kuprianov** [comment]
actually thank _you_ for the update: knowing that this might be useful for Hermes is a very good motivator for me to finish it sooner rather than later;)

**Comment by adizere** [comment]
Closing: deprioritized.

**Pull request closed without merging**
