### PR TITLE
Check header and update state

### PR DESCRIPTION
**Pull request by cezarad**
Closes: #XXX

## Description

- implements the ICS07 verification of the client update ``checkValidityAndUpdateState`` in https://github.com/cosmos/ibc/tree/master/spec/client/ics-007-tendermint-client 
- modifications in the tendermint testgen to make test pass with this extra check. 

______

For contributor use:

- [ ] Updated the __Unreleased__ section of [CHANGELOG.md](https://github.com/informalsystems/ibc-rs/blob/master/CHANGELOG.md) with the issue.
- [ ] If applicable: Unit tests written, added test to CI.
- [ ] Linked to Github issue with discussion and accepted design OR link to spec that describes this work.
- [ ] Updated relevant documentation (`docs/`) and code comments.
- [ ] Re-reviewed `Files changed` in the Github PR explorer.

### CODE REVIEW

**Review by adizere — CHANGES_REQUESTED** [review]
This seems almost ready, nice work Cezara!

Two questions:

- some tests are failing when I run locally `cargo test`, in particular

> test ics02_client::handler::update_client::tests::test_update_client_ok ... FAILED
... 
test ics02_client::handler::update_client::tests::test_update_client_ok_multiple ... FAILED
test ics26_routing::handler::tests::routing_module_and_keepers ... FAILED
test ics18_relayer::utils::tests::client_update_ping_pong ... FAILED


It seems that the cause is the newly added checks in the update client handler. Can you confirm that the tests are failing and see how we can fix them please?

- how do you think we should proceed with the code in `modules/src/ics07_tendermint/header.rs` which seems duplicating logic from tendermint-rs? Should we keep it there, or would it be better to work with the tendermint-rs team to adapt their interfaces, so that we avoid duplicating code?

**Comment by romac** [comment]
> * Should we keep it there, or would it be better to work with the tendermint-rs team to adapt their interfaces, so that we avoid duplicating code?

I think we should sort this out in tendermint-rs directly and adapt the light client code so that we do not need to duplicate this code.

**Comment by romac** [comment]
Note: there is also duplicated code between `modules/src/ics07_tendermint/header.rs` and `modules/src/ics07_tendermint/predicates.rs`

**Comment by adizere** [comment]
> > * Should we keep it there, or would it be better to work with the tendermint-rs team to adapt their interfaces, so that we avoid duplicating code?
> 
> I think we should sort this out in tendermint-rs directly and adapt the light client code so that we do not need to duplicate this code.

**Comment by cezarad** [comment]
> Note: there is also duplicated code between `modules/src/ics07_tendermint/header.rs` and `modules/src/ics07_tendermint/predicates.rs`

We can remove the predicates.rs I put all In headers

**Comment by cezarad** [comment]
mode to PR verification update #1252

**Pull request closed without merging**
