### PR TITLE
serde as string pub mod

### PR DESCRIPTION
**Pull request by dzmitry-lahoda**
Closes: #791

## Description

Serde as string is useful, Osmosis has impl and CosmWasm has impl and I will copy paste too. 
Serde repo has not such tool impl btw. Mostly hex/bytes things.

So at least one place, which also consistently supports no_std and other serializers and modes would be awesome.  Osmosis and CW-STD do not support no_std.

______

### PR author checklist:
- [x] Added changelog entry, using [`unclog`](https://github.com/informalsystems/unclog).
- [x] Added tests. No code changes, no tests.
- [x] Linked to GitHub issue.
- [x] Updated code comments and documentation (e.g., `docs/`).
- [x] Tagged *one* reviewer who will be the one responsible for shepherding this PR. @Farhad-Shabani as he is already on some serde decision things

### Reviewer checklist:

- [ ] Reviewed `Files changed` in the GitHub PR explorer.
- [ ] Manually tested (in case integration/unit/mock tests are absent).

### CODE REVIEW

**Comment by plafer** [comment]
Hey thank you for submitting this!

However, I don't understand what this achieves. Can you give me an example of something you can do with this change that you couldn't before?

**Comment by dzmitry-lahoda** [comment]
it achieves sharing serde which does not inflicts f32/f64 validation issues

**Comment by plafer** [comment]
Can you give us an example of which functions in the `serializers` module you would use, and for which structs?

Currently, these functions are not documented and only used internally, and if we're going to make them public, we need to understand what problem they solve.

EDIT: If I understand correctly, you would like to use the functions under `serializers::serde_string` to use on your own non-IBC structs?

**Comment by Farhad-Shabani** [comment]
As mentioned [here](https://github.com/cosmos/ibc-rs/pull/791#issuecomment-1665749572), it's best to keep these serializers for internal use only. We don't have sufficient info on potential uses, and can't really gauge the possible consequences outside of our own bubble. By the way, if you happen to use them with any of ibc types, feel free to reopen this!

**Pull request closed without merging**
