### PR TITLE
Split tasks spawned by CLI commands into their own modules

### PR DESCRIPTION
**Pull request by romac**
First small step towards #330

## Description

Split tasks spawned by CLI commands into their own modules.

______

For contributor use:

- [ ] Unit tests written
- [ ] Added test to CI if applicable 
- [ ] Updated CHANGELOG_PENDING.md
- [x] Linked to Github issue with discussion and accepted design OR link to spec that describes this work.
- [ ] Updated relevant documentation (`docs/`) and code comments
- [ ] Re-reviewed `Files changed` in the Github PR explorer

### CODE REVIEW

**Review by adizere — APPROVED** [review]
Cool, looks cleaner than before!

Some suggestion to try to further improve this (defer to next iteration of work towards #330):

- I suspect `relayer-cli/src/commands/utils.rs` can be deleted
- it would improve readability if all files in `commands.rs` have the same structure: definition of `pub struct xyzCmd`, then implementation of that struct, then `impl Runnable for xyzCmd`

**Review by adizere — APPROVED** [review]
Thanks! Looks good, I had nothing to comment.

**Comment by ancazamfir** [comment]
So `start` command doesn't start the monitors anymore? Just the light clients?  I think the `README.md` needs a small update.

**Comment by romac** [comment]
> So `start` command doesn't start the monitors anymore? Just the light clients? I think the `README.md` needs a small update.

It never did that AFAIK.

**Comment by ancazamfir** [comment]
> > So `start` command doesn't start the monitors anymore? Just the light clients? I think the `README.md` needs a small update.
> 
> It never did that AFAIK.

Just checked, it did before https://github.com/informalsystems/ibc-rs/pull/255, the `start` command was starting them together with the `event_handler` from the `relayer_task()`. We also have the `listen` command that just starts the monitors and prints the events.

**Review by ancazamfir — APPROVED** [review]
Looks good!

**Comment by romac** [comment]
> > > So `start` command doesn't start the monitors anymore? Just the light clients? I think the `README.md` needs a small update.
> > 
> > 
> > It never did that AFAIK.
> 
> Just checked, it did before #255, the `start` command was starting them together with the `event_handler` from the `relayer_task()`. We also have the `listen` command that just starts the monitors and prints the events.

Right, my bad! Since we are going to rewrite this code for v0 anyway, it doesn't really matter so I guess we can just go ahead and merge this.

**Pull request merged**
