### PR TITLE
Make token transfer events compatible with latest ibc-go

### LINKED ISSUE #495: Make token transfer events fully compatible with latest ibc-go
We're missing the [`sender` field](https://github.com/cosmos/ibc-go/blob/a4f7761981771b453fdb06203dba33a62b4b6317/modules/apps/transfer/ibc_module.go#L193) in most events (and maybe more fields too).

### PR DESCRIPTION
**Pull request by plafer**
Closes: #495

## Description

Only remaining field missing is `memo`, which will be added with https://github.com/cosmos/ibc-rs/issues/559.

______

### PR author checklist:
- [x] Added changelog entry, using [`unclog`](https://github.com/informalsystems/unclog).
- [ ] Added tests.
- [x] Linked to GitHub issue.
- [ ] Updated code comments and documentation (e.g., `docs/`).
- [ ] Tagged *one* reviewer who will be the one responsible for shepherding this PR.

### Reviewer checklist:

- [ ] Reviewed `Files changed` in the GitHub PR explorer.
- [ ] Manually tested (in case integration/unit/mock tests are absent).

### CODE REVIEW

**Review by Farhad-Shabani — COMMENTED** [review]
Just a question; in some places, there is a difference in how many events we emit compared to how many IBC-go emits (like [here](https://github.com/cosmos/ibc-go/blob/a24a6c65f14ceee5e9c8dd3f0f79d63439f1db23/modules/apps/transfer/keeper/msg_server.go#L45-L58) & [here](https://github.com/cosmos/ibc-go/blob/15cb75017adea8a1dfa08bfa1fea0351f58a82b3/modules/apps/transfer/ibc_module.go#L242-L270)). Does that have a specific reason?

**Comment by plafer** [comment]
For the first [link](https://github.com/cosmos/ibc-go/blob/a24a6c65f14ceee5e9c8dd3f0f79d63439f1db23/modules/apps/transfer/keeper/msg_server.go#L45-L58) (`sendTransfer` callback), we indeed forgot to output the `message` event type. I will fix this.

The second [link](https://github.com/cosmos/ibc-go/blob/15cb75017adea8a1dfa08bfa1fea0351f58a82b3/modules/apps/transfer/ibc_module.go#L242-L270) you shared (`OnAcknowledgement` callback) emits the same 2 events as ibc-rs (see [here](https://github.com/cosmos/ibc-rs/blob/291f3298ac588efc301f8a5d8a8907419f4ad136/crates/ibc/src/applications/transfer/context.rs#L367)), unless I'm mistaken.

**Comment by Farhad-Shabani** [comment]
> The second [link](https://github.com/cosmos/ibc-go/blob/15cb75017adea8a1dfa08bfa1fea0351f58a82b3/modules/apps/transfer/ibc_module.go#L242-L270) you shared (`OnAcknowledgement` callback) emits the same 2 events as ibc-rs (see [here](https://github.com/cosmos/ibc-rs/blob/291f3298ac588efc301f8a5d8a8907419f4ad136/crates/ibc/src/applications/transfer/context.rs#L367)), unless I'm mistaken.

Ahh, right, this one is correct

**Comment by plafer** [comment]
Blocked on https://github.com/cosmos/ibc-rs/issues/623

**Comment by plafer** [comment]
@Farhad-Shabani this is now ready for review!

**Review by Farhad-Shabani — APPROVED** [review]
👌🏻

**Pull request merged**
