### PR TITLE
Combine packet with packet command workers

### PR DESCRIPTION
**Pull request by soareschen**
Closes: #1715

## Description

______

### PR author checklist:
- [x] Added changelog entry, using [`unclog`](https://github.com/informalsystems/unclog).
- [x] Added tests: integration (for Hermes) or unit/mock tests (for modules). 
- [x] Linked to GitHub issue.
- [x] Updated code comments and documentation (e.g., `docs/`).

### Reviewer checklist:

- [x] Reviewed `Files changed` in the GitHub PR explorer.
- [x] Manually tested (in case integration/unit/mock tests are absent).

### CODE REVIEW

**Comment by romac** [comment]
LGTM, will leave it to @adizere to approve it.

**Review by adizere — COMMENTED** [review]
I think what's left that is important is to make sure we have reproduced reliably the error (as signaled in #1715), whether is it in an automatic test or a manual recipe. Soares did you manage to reproduce it?


Nit: changelog.

**Comment by soareschen** [comment]
> I think what's left that is important is to make sure we have reproduced reliably the error (as signaled in #1715), whether is it in an automatic test or a manual recipe. Soares did you manage to reproduce it?

I setup a branch (soares/packet-worker-recovery-master)[https://github.com/informalsystems/ibc-rs/tree/soares/packet-worker-recovery-master] that run the same supervisor test on master. The thing is the test also pass and the account sequence mismatch error has already been handled at the lower level.

```
2022-01-05T09:58:13.946115Z  INFO ibc_relayer::link::relay_path: [ibc-beta-afac1f12:transfer/channel-0 -> ibc-alpha-f85845b8] scheduling op. data with 1 msg(s) for Destination (height 0-43)
2022-01-05T09:58:14.143605Z  INFO ibc_relayer::link::relay_path: [ibc-beta-afac1f12:transfer/channel-0 -> ibc-alpha-f85845b8] relay op. data of 1 msgs(s) to Destination (hei
ght 0-43), delayed by: 197.413671ms [try 1/5]
2022-01-05T09:58:14.143762Z  INFO ibc_relayer::link::operational_data: [ibc-beta-afac1f12:transfer/channel-0 -> ibc-alpha-f85845b8] prepending Destination client update @ height 0-43
2022-01-05T09:58:14.237145Z DEBUG ibc_relayer::foreign_client: [ibc-beta-afac1f12 -> ibc-alpha-f85845b8:07-tendermint-1] MsgUpdateAnyClient from trusted height 0-28 to target height 0-43
2022-01-05T09:58:14.237570Z  INFO ibc_relayer::link::operational_data: [ibc-beta-afac1f12:transfer/channel-0 -> ibc-alpha-f85845b8] assembled batch of 2 message(s)
2022-01-05T09:58:14.237690Z DEBUG ibc_relayer::chain::cosmos: send_messages_and_wait_check_tx with 2 messages
2022-01-05T09:58:14.237788Z DEBUG ibc_relayer::chain::cosmos: [ibc-alpha-f85845b8] send_tx: sending 2 messages using account sequence 10
2022-01-05T09:58:14.238140Z DEBUG ibc_relayer::chain::cosmos: [ibc-alpha-f85845b8] send_tx: max fee, for use in tx simulation: Fee { amount: "3001stake", gas_limit: 3000000}
2022-01-05T09:58:14.247021Z ERROR ibc_relayer::chain::cosmos: [ibc-alpha-f85845b8] estimate_gas: failed to simulate tx. propagating error to caller: gRPC call failed with status: status: InvalidArgument, message: "account sequence mismatch, expected 11, got 10: incorrect account sequence: invalid request", details: [], metadata: MetadataMap { headers: {"content-type": "application/grpc"} }
2022-01-05T09:58:14.247087Z  WARN ibc_relayer::chain::cosmos: send_tx failed at estimate_gas step mismatching account sequence: dropping the tx & refreshing account sequence number
2022-01-05T09:58:14.250578Z DEBUG ibc_relayer::chain::cosmos: [ibc-alpha-f85845b8] send_tx: retrieved account sequence=11 number=3
2022-01-05T09:58:14.250775Z  WARN ibc_relayer::util::task: task PacketWorker(ibc-beta-afac1f12:transfer/channel-0 -> ibc-alpha-f85845b8) encountered ignorable error: link errror

Caused by:
   0: failed with underlying error
   1: gRPC call failed with status: status: InvalidArgument, message: "account sequence mismatch, expected 11, got 10: incorrect account sequence: invalid request", details:
 [], metadata: MetadataMap { headers: {"content-type": "application/grpc"} }

Location:
    /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/flex-error-0.4.4/src/tracer_impl/eyre.rs:10:9
2022-01-05T09:58:14.848052Z DEBUG ibc_integration_test::chain::exec: Executing command: gaiad --node tcp://localhost:35408 query bank balances cosmos18qr5vjak8zfdxrqzan4gsvq6dcajnjeplye63v --denom ibc/2D7DF22C789B9FB98A6B311760F5077E86A490D437F3FECEBC65A8CB00EA41A7 --output json
2022-01-05T09:58:14.963204Z  INFO ibc_relayer::link::relay_path: [ibc-alpha-f85845b8:transfer/channel-0 -> ibc-beta-afac1f12] generate messages from batch with 1 events
2022-01-05T09:58:14.964829Z DEBUG ibc_relayer::link::relay_path: [ibc-alpha-f85845b8:transfer/channel-0 -> ibc-beta-afac1f12] ibc-alpha-f85845b8 => SendPacketEv(SendPacket - h:0-51, seq:4, path:channel-0/transfer->channel-0/transfer, toh:0-1028, tos:Timestamp(2022-01-05T10:07:51.667870412Z)))
2022-01-05T09:58:14.972089Z DEBUG ibc_relayer::link::relay_path: [ibc-alpha-f85845b8:transfer/channel-0 -> ibc-beta-afac1f12] ibc-beta-afac1f12 <= /ibc.core.channel.v1.MsgRecvPacket from SendPacketEv(SendPacket - h:0-51, seq:4, path:channel-0/transfer->channel-0/transfer, toh:0-1028, tos:Timestamp(2022-01-05T10:07:51.667870412Z)))
2022-01-05T09:58:14.972154Z  INFO ibc_relayer::link::relay_path: [ibc-alpha-f85845b8:transfer/channel-0 -> ibc-beta-afac1f12] scheduling op. data with 1 msg(s) for Destination (height 0-52)
2022-01-05T09:58:15.268832Z  INFO ibc_relayer::link::relay_path: [ibc-alpha-f85845b8:transfer/channel-0 -> ibc-beta-afac1f12] relay op. data of 1 msgs(s) to Destination (height 0-52), delayed by: 296.64699ms [try 1/5]
2022-01-05T09:58:15.268880Z  INFO ibc_relayer::link::operational_data: [ibc-alpha-f85845b8:transfer/channel-0 -> ibc-beta-afac1f12] prepending Destination client update @ height 0-52
2022-01-05T09:58:15.297196Z DEBUG ibc_relayer::foreign_client: [ibc-alpha-f85845b8 -> ibc-beta-afac1f12:07-tendermint-2] MsgUpdateAnyClient from trusted height 0-48 to target height 0-52
2022-01-05T09:58:15.297448Z  INFO ibc_relayer::link::operational_data: [ibc-alpha-f85845b8:transfer/channel-0 -> ibc-beta-afac1f12] assembled batch of 2 message(s)
2022-01-05T09:58:15.297518Z DEBUG ibc_relayer::chain::cosmos: send_messages_and_wait_check_tx with 2 messages
2022-01-05T09:58:15.297605Z DEBUG ibc_relayer::chain::cosmos: [ibc-beta-afac1f12] send_tx: sending 2 messages using account sequence 11
2022-01-05T09:58:15.297814Z DEBUG ibc_relayer::chain::cosmos: [ibc-beta-afac1f12] send_tx: max fee, for use in tx simulation: Fee { amount: "3001stake", gas_limit: 3000000 }
2022-01-05T09:58:15.305878Z DEBUG ibc_relayer::chain::cosmos: [ibc-beta-afac1f12] estimate_gas: tx simulation successful, gas amount used: 137132
2022-01-05T09:58:15.306370Z DEBUG ibc_relayer::chain::cosmos: [ibc-beta-afac1f12] send_tx: using 137132 gas, fee Fee { amount: "151stake", gas_limit: 150846 }
2022-01-05T09:58:15.311807Z DEBUG ibc_relayer::chain::cosmos: [ibc-beta-afac1f12] send_tx: broadcast_tx_sync: Response { code: Ok, data: Data([]), log: Log("[]"), hash: transaction::Hash(53D32AEA34200119CFACD3CFD6C70159DAF1FB5C08CDCECBADD1986A484010BD) }
2022-01-05T09:58:15.311911Z  INFO ibc_relayer::link::relay_sender: [Async~>ibc-beta-afac1f12] response(s): 1; Ok:53D32AEA34200119CFACD3CFD6C70159DAF1FB5C08CDCECBADD1986A484010BD
2022-01-05T09:58:15.311955Z  INFO ibc_relayer::link::relay_path: [ibc-alpha-f85845b8:transfer/channel-0 -> ibc-beta-afac1f12] success
```

If you look into the body of [`execute_schedule`](https://github.com/informalsystems/ibc-rs/blob/soares/packet-worker-recovery-master/relayer/src/link/relay_path.rs#L1249-L1266), the only fallible operation it does is to call [`relay_from_operational_data`](https://github.com/informalsystems/ibc-rs/blob/soares/packet-worker-recovery-master/relayer/src/link/relay_path.rs#L499-L506), which already have the retry logic in there. So in both cases it would retry on an account sequence mismatch error in the inner logic already.

**Review by adizere — APPROVED** [review]
Excellent work!

Using branch https://github.com/informalsystems/ibc-rs/compare/soares/packet-worker-recovery-master

we were also able to reproduce the failure with

```
$ cargo test -p ibc-integration-test -- test_supervisor
... [omitted]
failures:
    tests::supervisor::test_supervisor

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 6 filtered out; finished in 63.15s
```

**Pull request merged**
