### PR TITLE
Split out ibc-clients crate

### PR DESCRIPTION
**Pull request by seanchen1991**
Part of: #965 

## Description

______

### PR author checklist:
- [ ] Added changelog entry, using [`unclog`](https://github.com/informalsystems/unclog).
- [ ] Added tests.
- [ ] Linked to GitHub issue.
- [ ] Updated code comments and documentation (e.g., `docs/`).
- [ ] Tagged *one* reviewer who will be the one responsible for shepherding this PR.

### Reviewer checklist:

- [ ] Reviewed `Files changed` in the GitHub PR explorer.
- [ ] Manually tested (in case integration/unit/mock tests are absent).

### CODE REVIEW

**Comment by seanchen1991** [comment]
@Farhad-Shabani Two things before this PR is fully ready for review and merging:
1. The `ibc_core::extra::tendermint::validate_self_client` module complains about not being to find the `latest_height` method on the `ClientState` type (imported from `ibc_client_tendermint_types::client_state::ClientState`). This is because the `latest_height` method is implemented for `ClientState` as part of the `ClientStateCommon` trait: this trait implementation exists in the handlers part of the `ics07-tendermint` crate, not the `ics07-tendermint/types` sub-crate. How should we go about resolving this? Should the `ClientStateCommon` trait implementation be moved to the types sub-crate? We could also opt to move the `latest_height` function out of the `ClientStateCommon` trait and have it exist standalone in the `types` sub-crate. What's the preferred way to address this?
2. The `ibc-testkit` crate's import paths still need to be updated.

**Comment by Farhad-Shabani** [comment]
> Two things before this PR is fully ready for review and merging

Big thanks @seanchen1991 for taking care of the clients migration! 🙌
I made a few more tweaks to the `ibc-core` [PR](https://github.com/cosmos/ibc-rs/pull/969). Some code shuffled around, and I ditched `ibc-core-extra` crate, moving its codebase to the other right crates. I've updated your PR as well to sync up with these changes and also tackled issues you pointed out earlier.

**Comment by Farhad-Shabani** [comment]
fyi: to avoid confusion arising from the varied use of `ClientState` in different types and implementations, I've updated the naming around. The newly defined newtype `ClientState` is now named `ClientStateWrapper`, while the original Tendermint `ClientState` struct has been preserved as `TmClientState` wherever it is imported. The term `ClientState` still refers to the trait, ensuring consistency in naming with the `ConsensusState` as well. Hope it works.

**Comment by Farhad-Shabani** [comment]
Merged this PR to have a smoother review of changes within a consolidated branch.

**Pull request merged**
