### PR TITLE
fix: make client response fields public + remove reduntant `QueryConnectionChannelsRequest`

### PR DESCRIPTION
**Pull request by Farhad-Shabani**
Closes: #XXX

## Description
As a follow-up to PR #1129, this PR fixes some small inconsistencies.

______

### PR author checklist:
- [X] Tagged *one* reviewer who will be the one responsible for shepherding this PR.

### Reviewer checklist:

- [ ] Reviewed `Files changed` in the GitHub PR explorer.
- [ ] Manually tested (in case integration/unit/mock tests are absent).

### CODE REVIEW

**Comment by rnbguy** [comment]
Good catches! Additionally, I realized:
- `impl Protobuf<RawType> for DomainType` is not required.
- `request.rs` only requires `impl TryFrom<RawType> for DomainType`.
- `response.rs` only requires `impl From<DomainType> for RawType`.

**Comment by Farhad-Shabani** [comment]
> Good catches! Additionally, I realized:
> 
> * `impl Protobuf<RawType> for DomainType` is not required.
> * `request.rs` only requires `impl TryFrom<RawType> for DomainType`.
> * `response.rs` only requires `impl From<DomainType> for RawType`.


From the host's perspective, we definitely only need the conversion direction you mentioned. However, it's crucial that these types also cater to relayers, so we'll need to ensure the other direction is well-supported too.

Regarding `Protobuf`, I'm still leaning towards implementing it because it offers integrators convenient access to some useful encode/decode methods.

**Comment by rnbguy** [comment]
> it's crucial that these types also cater to relayers

> Regarding Protobuf, I'm still leaning towards implementing it because it offers integrators convenient access to some useful encode/decode methods.

Ah. I see. In that case, I am totally fine implementing these. But I mentioned this because this requirement is not maintained for all domain<>raw types.

Shouldn't we implement `impl Protobuf<RawType> for DomainType` for all?

**Comment by Farhad-Shabani** [comment]
> Shouldn't we implement `impl Protobuf<RawType> for DomainType` for all?

Correct. Currently, we haven't been able to implement that for all cases. I've explained the reason in the ibc-query's [README](https://github.com/cosmos/ibc-rs/tree/main/ibc-query#remarks).
We are in discussions with the ibc-go team to update the request protobuf definitions, incorporating the query height in relevant types. Therefore, we'll need to wait until that change is applied.

**Review by rnbguy — APPROVED** [review]
LGTM :sparkles:

**Comment by rnbguy** [comment]
@Farhad-Shabani Thanks for your responses. Now everything is good :slightly_smiling_face:

**Pull request merged**
