### PR TITLE
refactor: check client status active when verify consensus state

### LINKED ISSUE #1088: bug(core): client creation only checks if the client is frozen
## Bug Summary

only non-frozen status is checked at client creation. we should just check if the client is active.

## Details

https://github.com/cosmos/ibc-rs/blob/3b260e209ec6111c1dc2520d14f65fd605fdc834/ibc-core/ics02-client/src/handler/create_client.rs#L35

~should be refactored to `if !status.is_active() { ... }`.~

The `status()` is the status of the stored client state and its corresponding stored consensus state. So this doesn't include the provided `ConsensusState`. So its status needs to be checked locally.

IBC-go also [checks for active status](https://github.com/cosmos/ibc-go/blob/c3ba0d03a99965471cd2a3c0ff0bd16875eeca78/modules/core/02-client/keeper/client.go#L41), instead of just non-frozen status.

## Version

`v0.50.0`

### PR DESCRIPTION
**Pull request by hoank101**
Closes: #1088

## Description

______

### PR author checklist:
- [ ] Added changelog entry, using [`unclog`](https://github.com/informalsystems/unclog).
- [ ] Added tests.
- [ ] Linked to GitHub issue.
- [ ] Updated code comments and documentation (e.g., `docs/`).
- [ ] Tagged *one* reviewer who will be the one responsible for shepherding this PR.

### Reviewer checklist:

- [ ] Reviewed `Files changed` in the GitHub PR explorer.
- [ ] Manually tested (in case integration/unit/mock tests are absent).

### CODE REVIEW

**Comment by rnbguy** [comment]
Thanks for your PR, @hoank101 ! But this issue is a bit nuanced, and my suggestion on the issue ~is~ was misleading.

`is_active` call on unstored `client_id` will return `Frozen` or `Expired`. `Expired` case happens because there is no consensus state present for that `client_id` - which is assumed to be pruned.

That's why you needed to insert a consensus state before executing `MsgCreateClient`. But that's not possible on live chain - and, this logic will always fail.

We need to check for the `Expired` status for the proved `ConsensusState` locally. To execute this nicely will require some careful changes in the traits.

**Comment by hoank101** [comment]
> Thanks for your PR, @hoank101 ! But this issue is a bit nuanced, and my suggestion on the issue ~is~ was misleading.
> 
> `is_active` call on unstored `client_id` will return `Frozen` or `Expired`. `Expired` case happens because there is no consensus state present for that `client_id` - which is assumed to be pruned.
> 
> That's why you needed to insert a consensus state before executing `MsgCreateClient`. But that's not possible on live chain - and, this logic will always fail.
> 
> We need to check for the `Expired` status for the proved `ConsensusState` locally. To execute this nicely will require some careful changes in the traits.

thank you for feedback, i will update logic

**Comment by rnbguy** [comment]
Note how it's being handled in ibc-go [here](https://github.com/cosmos/ibc-go/blob/c3ba0d03a99965471cd2a3c0ff0bd16875eeca78/modules/core/02-client/keeper/client.go#L37-L43). The status is checked after the consensus state is stored.

But in ibc-rs, we separate _validation_ and _execution_. If we followed ibc-go, we could have checked `status.is_active()` in `execute()` after the following.

https://github.com/cosmos/ibc-rs/blob/3b260e209ec6111c1dc2520d14f65fd605fdc834/ibc-core/ics02-client/src/handler/create_client.rs#L67-L71

But this breaks the convention of our design.

**Comment by Farhad-Shabani** [comment]
Closing this as addressed in https://github.com/cosmos/ibc-rs/pull/1294.
Thank you again @hoank101 for jumping in to tackle this issue.

**Pull request closed without merging**
