### PR TITLE
ics26_routing: Derive Hash for ModuleId

### PR DESCRIPTION
**Pull request by kevinji**
Signed-off-by: Kevin Ji <1146876+kevinji@users.noreply.github.com>

## Description

Derive Hash for ModuleId so it can be stored in a HashMap.
______

### PR author checklist:
- [X] Added changelog entry, using [`unclog`](https://github.com/informalsystems/unclog).
- [ ] Added tests.
- [ ] Linked to GitHub issue.
- [ ] Updated code comments and documentation (e.g., `docs/`).
- [ ] Tagged *one* reviewer who will be the one responsible for shepherding this PR.

### Reviewer checklist:

- [ ] Reviewed `Files changed` in the GitHub PR explorer.
- [ ] Manually tested (in case integration/unit/mock tests are absent).

### CODE REVIEW

**Comment by DaviRain-Su** [comment]
You can use BtreeMap, So We don't need this change.

**Comment by hu55a1n1** [comment]
Thanks for the PR @kevinji! 
A `HashMap` uses a randomly seeded hashing algorithm that results in a random iteration order and could introduce non-determinism in on-chain code. Please use `BTreeMap` as @DaviRain-Su suggested. 
Please feel free to reopen if you have other needs that require the `Hash` impl. :pray:

**Comment by kevinji** [comment]
Hey I had two questions:

- I'm writing some code for Solana where rand is not enabled, so I believe HashMap is deterministic. Is this use case not supported?
- I'm also making ModuleId consistent with PortId and ChannelId which do derive Hash. Is there a reason why ModuleId shouldn't work the same way?

**Comment by hu55a1n1** [comment]
Thanks for providing this additional context. I think this is a valid use case.

**Review by hu55a1n1 — COMMENTED** [review]
We're missing a changelog entry. Would you like to add one? Otherwise please feel free to delegate to us and we'll add it. See here for details on how to add a changelog using unclog -> https://github.com/cosmos/ibc-rs/blob/main/CONTRIBUTING.md#changelog.

**Comment by kevinji** [comment]
Just added a changelog entry; let me know if it needs any changes.

**Review by hu55a1n1 — APPROVED** [review]
:ok_hand:

**Pull request merged**
