### PR TITLE
simplify get all event from tx logic

### PR DESCRIPTION
**Pull request by lyqingye**
reuse code  [from_tx_response_event](https://github.com/informalsystems/ibc-rs/blob/master/modules/src/events.rs#L168) for [get_all_events](https://github.com/informalsystems/ibc-rs/blob/master/relayer/src/event/rpc.rs#L15)

## Description

extract IBC packets directly from events of tx result 

______

For contributor use:

- [ ] Added a changelog entry, using [`unclog`](https://github.com/informalsystems/unclog).
- [ ] If applicable: Unit tests written, added test to CI.
- [ ] Linked to Github issue with discussion and accepted design OR link to spec that describes this work.
- [ ] Updated relevant documentation (`docs/`) and code comments.
- [ ] Re-reviewed `Files changed` in the Github PR explorer.

### CODE REVIEW

**Comment by RiccardoM** [comment]
@adizere Can we have an update on this? IBC integration is going to play a big role inside the Cosmos ecosystem, and they rely on end block events for sending back the result of their async work

**Comment by romac** [comment]
@RiccardoM Can you please provide some rationale as to why this change is needed and how it helps with your use case?

**Comment by romac** [comment]
@lyqingye @RiccardoM @RiccardoM Can you please provide some rationale as to why this change is needed and how it helps with your use case?

**Comment by RiccardoM** [comment]
> @lyqingye @RiccardoM Can you please provide a more detailed rationale as to why this change is needed and how it helps with the use case?

I think [this](https://github.com/informalsystems/ibc-rs/issues/1231#issuecomment-897294980) better explains it

**Comment by lyqingye** [comment]
> @lyqingye @RiccardoM Can you please provide a more detailed rationale as to why this change is needed and how it helps with the use case?

The purpose of this change is to extract IBC send_packets in any transaction. The difference [build_event](https://github.com/informalsystems/ibc-rs/blob/master/relayer/src/event/rpc.rs#L59) is that [build_event](https://github.com/informalsystems/ibc-rs/blob/master/relayer/src/event/rpc.rs#L59) only extracts send_packets from specified action of transactions, such as "transfer" | "register" | "send".

Because IBC send_packets of some chains are generated by custom transactions, the Hermes cannot relay this packets

**Comment by romac** [comment]
@ancazamfir Can this be closed now that https://github.com/informalsystems/ibc-rs/pull/1172 is in?

**Comment by ancazamfir** [comment]
> @ancazamfir Can this be closed now that #1172 is in?

Yes!

**Comment by romac** [comment]
Superseded and fixed in #1172.

**Pull request closed without merging**
