### PR TITLE
implement ics06 solomachine client

### LINKED ISSUE #641: Implement an Ics06 SoloMachine client
## Feature Summary

 Implement an Ics06 SoloMachine client.

link: https://github.com/cosmos/ibc-go/tree/main/modules/light-clients/06-solomachine

## Proposal

you can assign me the task and I will complete the requirement.

### PR DESCRIPTION
**Pull request by DaviRain-Su**
Closes: #641 

## Description

The goal of this PR is to implement the [ics06 solomachine client](https://github.com/cosmos/ibc-go/tree/main/modules/light-clients/06-solomachine) in `ibc-go`. During the process, I used some types from the cosmos-rust repository, but using types from this repository resulted in version mismatch issues between `ibc-proto` and `cosmos-sdk-proto`. So, my solution was to replace the proto used in the `cosmrs` repository with `ibc-proto`. 
Here are some issues encountered: 
1. `cosmrs` does not support `no-std`, https://github.com/cosmos/cosmos-rust/pull/404
2. Version mismatch issues between `ibc-proto` and `cosmos-sdk-proto,` https://github.com/cosmos/ibc-proto-rs/pull/102 https://github.com/cosmos/cosmos-rust/pull/404
3. The `tx::signing` types are not implemented in `cosmrs`. https://github.com/cosmos/cosmos-rust/pull/405

______

### PR author checklist:
- [ ] Added changelog entry, using [`unclog`](https://github.com/informalsystems/unclog).
- [ ] Added tests.
- [ ] Linked to GitHub issue.
- [ ] Updated code comments and documentation (e.g., `docs/`).
- [ ] Tagged *one* reviewer who will be the one responsible for shepherding this PR.

### Reviewer checklist:

- [ ] Reviewed `Files changed` in the GitHub PR explorer.
- [ ] Manually tested (in case integration/unit/mock tests are absent).

### CODE REVIEW

**Comment by plafer** [comment]
Hey @DaviRain-Su this is a great initiative! However, since we implemented [ADR 4](https://github.com/cosmos/ibc-rs/blob/main/docs/architecture/adr-004-light-client-crates-extraction.md), light clients no longer need to live in ibc-rs. The ibc-rs team currently maintains the tendermint light client because our team has that expertise, but the goal is really to not have to maintain every light client out there. Here's what I suggest:

1. Move your implementation to a new repository
2. We add a "list of third-party light client implementations" in our README, link to your crate there so that other people can find it.

Also note that with #296, there will be breaking changes to the `ClientState` trait. However they shouldn't be too difficult to fix.

**Comment by DaviRain-Su** [comment]
I move this code to https://github.com/octopus-network/ics06-solomachine

**Comment by plafer** [comment]
Awesome! Is the implementation complete? If so, then we'll add a reference to it in our README

**Comment by DaviRain-Su** [comment]
> 

Have not, just on working. breaking on  lastet implement verifySignature function.

**Comment by plafer** [comment]
I'll close this PR then, and please open a new issue (requesting that we add your crate to our README) when your implementation is ready!

**Pull request closed without merging**
