### PR TITLE
fix(ics-23): Auto-derive `serde::Serialize` for `CommitmentPrefix`

### LINKED ISSUE #1229: Fix inconsistencies when de/serializing `CommitmentPrefix`
## Feature Summary

Raised by @soareschen:

> It looks like there are some inconsistencies between the JSON serialization and deserialization of ConnectionEnd in ibc-rs. I tried to query for the connection end from sov-ibc, and when try to parse the response using QueryConnectionResponse, I got the error:
>
> `Error: ParseError(Error("invalid type: string \"ibc\", expected struct CommitmentPrefix", line: 1, column: 139))`
>
> So it seems like the commitment_prefix field is serialized into string during serialization, but is expected to be wrapped inside a CommitmentPrefix wrapper field during JSON deserialization.
>
> I think the culprit is probably here:
```rs
#[cfg_attr(feature = "serde", derive(serde::Deserialize))]
pub struct CommitmentPrefix {
    bytes: Vec<u8>,
}

#[cfg(feature = "serde")]
impl serde::Serialize for CommitmentPrefix {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        format!("{self:?}").serialize(serializer)
    }
}
```
> The Deserialize instance is auto derived using serde, but the Serialize instance is manually implemented to serialize it as string

## Proposal

Either auto-derive `serde::Serialize` as well for `CommitmentPrefix`, or manually deserialize it so that parsing is consistent.

### PR DESCRIPTION
**Pull request by seanchen1991**
Closes: #1229 

## Description

______

### PR author checklist:
- [ ] Added changelog entry, using [`unclog`](https://github.com/informalsystems/unclog).
- [ ] Added tests.
- [ ] Linked to GitHub issue.
- [ ] Updated code comments and documentation (e.g., `docs/`).
- [ ] Tagged *one* reviewer who will be the one responsible for shepherding this PR.

### Reviewer checklist:

- [ ] Reviewed `Files changed` in the GitHub PR explorer.
- [ ] Manually tested (in case integration/unit/mock tests are absent).

### CODE REVIEW

**Comment by soareschen** [comment]
I think this is a reasonable fix. However, we may want to consider whether it is fine for breaking compatibility in this case. Let's wait for @rnbguy and @romac to review and discuss the changes.

**Comment by romac** [comment]
I think that's fine, better to break compatibility now and have consistent serialization than the reverse.

**Comment by soareschen** [comment]
Sounds good. @seanchen1991 let's add a changelog to indicate the breaking change?

**Comment by seanchen1991** [comment]
@soareschen, you mentioned that you opened a fork that manually implements deserialization from `String`. Would that route be preferable than opting to auto-derive `Serialize`?

**Comment by seanchen1991** [comment]
Oh, I just saw [this](https://github.com/cosmos/ibc-rs/issues/1229#issuecomment-2117001922) comment, which makes me think we should just opt to auto-derive `Serialize` instead of manually implement `Deserialize`.

**Comment by soareschen** [comment]
Yes, the custom fix is at https://github.com/cosmos/ibc-rs/tree/soares/fix-commitment-prefix-deserialize. But we should serialize and deserialize it as bytes, as the current behavior for serializing non-UTF8 commitment prefix is incorrect.

**Review by soareschen — APPROVED** [review]

**Pull request merged**
