### PR TITLE
Raise the WebSocket connection's `max_message_size` to 256MB

### PR DESCRIPTION
**Pull request by romac**
Closes: #1299

## Description

Increase the maximum size of WebSocket messages to 256MB to deal with Osmosis nodes sometimes emitting huge events.
Also increases the max frame size to 64MB to avoid splitting such messages over too many frames.

______

For contributor use:

- [ ] Added a changelog entry, using [`unclog`](https://github.com/informalsystems/unclog).
- [ ] If applicable: Unit tests written, added test to CI.
- [ ] Linked to Github issue with discussion and accepted design OR link to spec that describes this work.
- [ ] Updated relevant documentation (`docs/`) and code comments.
- [ ] Re-reviewed `Files changed` in the Github PR explorer.

### CODE REVIEW

**Comment by adizere** [comment]
The only way to test this is in production with the Osmosis epoch blocks?

CC @mircea-c & @greg-szabo I think this may be of interest!

**Comment by mircea-c** [comment]
Sorry about the delay everyone. I've started running this for the osmosis relayer. Will report back next week.

**Comment by adizere** [comment]
Should we drop this PR? It seems like we don't understand the consequence of the changes in this PR, and Thane managed to fix (most of) our WS problems with https://github.com/tendermint/tendermint/pull/7230.

**Comment by romac** [comment]
Agreed, let's close.

**Pull request closed without merging**
