### PR TITLE
Add ICS07 client upgrade to the MBT tests

### LINKED ISSUE #1311: Add ICS 07 (Client Upgrade) to the MBT tests
## Crate

`ibc-relayer`

## Summary

Add ICS 07 (Client Upgrade) to the MBT tests.

____

#### For Admin Use

- [x] Not duplicate issue
- [x] Appropriate labels applied
- [x] Appropriate milestone (priority) applied
- [x] Appropriate contributors tagged
- [x] Contributor assigned/self-assigned

### PR DESCRIPTION
**Pull request by jtremback**
Closes #1311

## Description

This PR adds capability to model a client upgrade to the TLA+ testing spec. It also makes some modifications to the rust MBT tests to run this capability as an MBT test.

Changes in the spec:
- Replace the single integer `Height` with a record containing `RevisionHeight` and `RevisionNumber`, as specified in ICS07.
- Add `ICS07_UpgradeClient` operator which:
- - Checks if a client exists
- - Checks if the new height has a higher revision number than the old height
- - Updates the client to the new revision number

Changes in the Rust:
- Replace the single integer `Height` with `ibc::Height`.
- Add boilerplate to translate actions and outcomes from TLA+ traces to Rust
- Key the `IbcTestRunner.contexts` hashmap with a chainID that does not include the revision number. This allows tests to keep working when the revision number changes.

Caveats: The state space has become much bigger from the addition of multiple possible revision numbers. Some of the MBT tests now take minutes to run. We may not want to merge this PR until this is fixed. An easy fix that occurs to me is making Modelator cache TLA+ traces and invalidate this cache when the TLA+ file changes. I will also probably spend some time trying to restrict the state space of this model.

______

For contributor use:

- [x] Added a changelog entry, using [`unclog`](https://github.com/informalsystems/unclog).
- [ ] If applicable: Unit tests written, added test to CI.
- [ ] Linked to Github issue with discussion and accepted design OR link to spec that describes this work.
- [x] Updated relevant documentation (`docs/`) and code comments.
- [x] Re-reviewed `Files changed` in the Github PR explorer.

### CODE REVIEW

**Comment by jtremback** [comment]
More on the state space / test time thing.

"rust-stable" CI tests on this PR took 13m 43s
Last other PR I checked ran "rust-stable" in 10m 16s

On my local, `cargo test` on master takes 189.45s, while `cargo test` on this branch takes 733.33s.

@adizere told me we try not to merge stuff that makes the tests take longer than 10m. I assume he was talking about the tests on Github CI. This PR exceeds that by about 3 minutes, so I will need to try to fix that.

**Comment by adizere** [comment]
> @adizere told me we try not to merge stuff that makes the tests take longer than 10m. I assume he was talking about the tests on Github CI. This PR exceeds that by about 3 minutes, so I will need to try to fix that.

Yes, the [GitHub CI](https://github.com/informalsystems/ibc-rs/actions). More context on this: our current CI takes on average 11 minutes; the longest task is the [E2E tests](https://github.com/informalsystems/ibc-rs/actions/runs/1138527738/workflow) and the next most time intensive task is the [Rust](https://github.com/informalsystems/ibc-rs/actions/runs/1138525863/workflow) tests, which can take 10min. This is not very often a bottleneck, but we would prefer to not increase the delay further -- and if it were a low-hanging fruit we _would_ reduce that time.

**Comment by jtremback** [comment]
CI time for Rust / test-stable (pull_request) is down to 10m 47s- can this be merged? To get any lower, I think I will need to rewrite the TLA+ spec.

**Comment by hu55a1n1** [comment]
IMHO, we could have a dedicated workflow in the future (for long-running and cross-chain tests) that is only triggered on release -> https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#onevent_nametypes
We could also improve it to use something like `git bisect` to find and report the first commit that caused the tests to fail.

**Review by romac — APPROVED** [review]
Great stuff, @jtremback! Test suite running time looks good to me, although we don't have much margin yet wrt the E2E test suite running time, but we can address that in time.

**Pull request merged**
