### PR TITLE
Release v0.36.0

### PR DESCRIPTION
**Pull request by plafer**

### CODE REVIEW

**Review by Farhad-Shabani — APPROVED** [review]
:pray:
Should we merge this after updating basecoin-rs and passing the CI?

**Comment by Farhad-Shabani** [comment]
Would it work with you also fix [the broken link under v0.34.0](https://github.com/cosmos/ibc-rs/blob/main/CHANGELOG.md#v0340) along with this PR?

**Comment by Farhad-Shabani** [comment]
Also, I just noticed we haven't included issue 563 under the "Bug" title in the changelog

**Comment by plafer** [comment]
> Would it work with you also fix [the broken link under v0.34.0](https://github.com/cosmos/ibc-rs/blob/main/CHANGELOG.md#v0340) along with this PR?

oops only saw that after merging

> Also, I just noticed we haven't included issue 563 under the "Bug" title in the changelog

We did, it's [here](https://github.com/cosmos/ibc-rs/blob/271c48d860294503eff06ec927429ac43e469522/.changelog/v0.36.0/bug/563-emit-message-events.md#L1)

**Comment by plafer** [comment]
> Also, I just noticed we haven't included issue 563 under the "Bug" title in the changelog

ahhh `CHANGELOG.md`, right. I'll fix those in another PR.

**Pull request merged**
