### PR TITLE
Support custom extension options when building tx

### PR DESCRIPTION
**Pull request by yihuang**
## Description

Closes: #2566

Support custom extension options to be able to specify max_priority_price in ethermint dynamic fee tx. 

______

### PR author checklist:
- [x] Added changelog entry, using [`unclog`](https://github.com/informalsystems/unclog).
- [ ] Added tests: integration (for Hermes) or unit/mock tests (for modules).
- [x] Linked to GitHub issue.
- [ ] Updated code comments and documentation (e.g., `docs/`).
- [ ] Tagged *one* reviewer who will be the one responsible for shepherding this PR.

### Reviewer checklist:

- [ ] Reviewed `Files changed` in the GitHub PR explorer.
- [ ] Manually tested (in case integration/unit/mock tests are absent).

### CODE REVIEW

**Comment by romac** [comment]
If I understand correctly, this would be used as follows in the config file:

```toml
[[chains]]
id = '...'

# ...

extension_options = [
  { type = "ethermint_dynamic_fee", value = "10" }
]
```

Right?

For our understanding, can you please elaborate on what this means for Ethermint? It's not super clear in the issue what are the semantics of that extension.

**Comment by yihuang** [comment]
> If I understand correctly, this would be used as follows in the config file:
> 
> 
> 
> ```toml
> 
> [[chains]]
> 
> id = '...'
> 
> 
> 
> # ...
> 
> 
> 
> extension_options = [
> 
>   { type = "ethermint_dynamic_fee", value = "10" }
> 
> ]
> 
> ```
> 
> 
> 
> Right?
> 
> 
> 
> For our understanding, can you please elaborate on what this means for Ethermint? It's not super clear in the issue what are the semantics of that extension.

Yes, there's some contexts here: https://github.com/informalsystems/ibc-rs/issues/2350#issuecomment-1216607676, it's needed to fix the reorder issue after we enable the tx priority and feemarket.

**Comment by yihuang** [comment]
We did an integration test with it: https://github.com/crypto-org-chain/cronos/pull/652

**Comment by yihuang** [comment]
@romac what's your opinion on this? this is necessary for all ethermint chains, including cronos and evmos.

**Comment by romac** [comment]
I am in favor of this change, thank you very much for suggesting it. Unfortunately, it won't make it into v1.0 (which will go very soon) but we will merge and release it into Hermes v1.1.

**Review by romac — APPROVED** [review]

**Pull request merged**
