### PR TITLE
Fix panic in conn open try when no connection id is provided

### PR DESCRIPTION
**Pull request by vitorenesduarte**
Closes: #XXX

## Description

Currently, a conn open try can only succeed if some `previous_connection_id` is provided in the `MsgConnectionOpenTry`:
https://github.com/informalsystems/ibc-rs/blob/b1b9dac6132a2fd2a86fa1c6f0179f47db3e3454/modules/src/ics03_connection/msgs/conn_open_try.rs#L26-L35
However, to have a valid `previous_connection_id`, one has to have a successful conn open try. This circular dependency makes it so that it's never possible to have successful conn open try.

This issue was found during the MBT work (#601). I tried to add a regression test but didn't find an easy way to do it. The best candidate was the `routing_module_and_keepers` test in `ics26_routing/handler.rs`: https://github.com/informalsystems/ibc-rs/blob/b1b9dac6132a2fd2a86fa1c6f0179f47db3e3454/modules/src/ics26_routing/handler.rs#L152-L316

There's a single chain here, which I think means it's not possible to have a successful conn open try. I've also noticed that the tests here don't check that the returned error matches the expected error. This is done in the `IBCTestExecutor` introduced in #601. Maybe at some point it will be possible to reuse this test executor to write these simple unit tests.

______

For contributor use:

- [ ] Updated the __Unreleased__ section of [CHANGELOG.md](https://github.com/informalsystems/ibc-rs/blob/master/CHANGELOG.md) with the issue.
- [ ] If applicable: Unit tests written, added test to CI.
- [ ] Linked to Github issue with discussion and accepted design OR link to spec that describes this work.
- [ ] Updated relevant documentation (`docs/`) and code comments.
- [ ] Re-reviewed `Files changed` in the Github PR explorer.

### CODE REVIEW

**Review by ancazamfir — COMMENTED** [review]
Looks good as a quick fix. But I think we should have a consistent approach with client and channel handling. I thought we decided when we re-wrote the client handler to return an id from `process()`. @adizere ? Looking at channels now, we do the same as in connection.

**Comment by adizere** [comment]
> Looks good as a quick fix. But I think we should have a consistent approach with client and channel handling. I thought we decided when we re-wrote the client handler to return an id from `process()`. @adizere ? Looking at channels now, we do the same as in connection.

Currently only ICS02 performs identifier selection and returns that from `process`.

We should adapt both ICS03 (and ICS04) to return identifiers from `process`. The changes should not be difficult. I agree we need a consistent approach, and the approach in ICS02 should work.

**Comment by ancazamfir** [comment]
> We should adapt both ICS03 (and ICS04) to return identifiers from process. The changes should not be difficult. I agree we need a consistent approach, and the approach in ICS02 should work.

Sounds good. I will leave it up to you @vitorenesduarte if you want to do it in this PR or we do it in a separate one. I opened #622, please mention in `Closes: #XXX` if you decide to fix it here.

**Comment by vitorenesduarte** [comment]
> > We should adapt both ICS03 (and ICS04) to return identifiers from process. The changes should not be difficult. I agree we need a consistent approach, and the approach in ICS02 should work.
> 
> Sounds good. I will leave it up to you @vitorenesduarte if you want to do it in this PR or we do it in a separate one. I opened #622, please mention in `Closes: #XXX` if you decide to fix it here.

Let's do it in another PR.

**Review by adizere — APPROVED** [review]
Looks good, thank you.

**Comment by romac** [comment]
@vitorenesduarte Great stuff! Can you please also create an issue, mention it in the body of this PR and update the CHANGELOG accordingly in a follow-up PR?

**Comment by vitorenesduarte** [comment]
> @vitorenesduarte Great stuff! Can you please also create an issue, mention it in the body of this PR and update the CHANGELOG accordingly in a follow-up PR?

Thanks @romac. Done in https://github.com/informalsystems/ibc-rs/pull/627.

**Pull request merged**
