### PR TITLE
change ethermint address_type to ethermint.crypto.v1.ethsecp256k1.PubKey

### PR DESCRIPTION
**Pull request by Kukoomomo**
Close: #1972

### CODE REVIEW

**Review by adizere — COMMENTED** [review]
Thank you for your contribution. Concept OK from me since this is a minor change!

Note that we don't have domain expertise on Evmos chains or Ethermint address types in our team. Pinging part of the team that added Ethermint support in ibc-rs, since they might encounter the same problem as you: @tomtau @devashishdxt @xlab @leejw51crypto. We can merge this after at least one of them chimes in.

**Comment by Kukoomomo** [comment]
>

**Comment by Kukoomomo** [comment]
> Thank you for your contribution. Concept OK from me since this is a minor change!
> 
> Note that we don't have domain expertise on Evmos chains or Ethermint address types in our team. Pinging part of the team that added Ethermint support in ibc-rs, since they might encounter the same problem as you: @tomtau @devashishdxt @xlab @leejw51crypto. We can merge this after at least one of them chimes in.

thanks

**Review by devashishdxt — APPROVED** [review]

**Comment by devashishdxt** [comment]
LGTM

**Review by romac — APPROVED** [review]

**Pull request merged**
