### PR TITLE
gm 0.1.0 - extra wallet addresses, JSON output, minor fixes

### PR DESCRIPTION
**Pull request by greg-szabo**
Closes: #XXX

## Description
This change adds the `extra_wallets` parameter to the `gm` configuration. The user can define how many extra wallets to create for the network.

It also adds the option to print JSON output by setting the environ,ment variable `OUTPUT="json"`.
______

For contributor use:

- [x] Added a changelog entry, using [`unclog`](https://github.com/informalsystems/unclog).
- [ ] If applicable: Unit tests written, added test to CI.
- [ ] Linked to Github issue with discussion and accepted design OR link to spec that describes this work.
- [ ] Updated relevant documentation (`docs/`) and code comments.
- [X] Re-reviewed `Files changed` in the Github PR explorer.

### CODE REVIEW

**Comment by greg-szabo** [comment]
I kept `extra_wallets=0` for backward UX. (Which will still create the "old" `wallet` wallet.) Should I change it to `1` so you always get an extra wallet?

**Review by adizere — COMMENTED** [review]
> I kept `extra_wallets=0` for backward UX. (Which will still create the "old" `wallet` wallet.) Should I change it to `1` so you always get an extra wallet?

Thanks for the changes Greg! For me `0` is fine.

I would request one feature though: I'd expect when running `gm hermes keys` that all wallet* for each chain to be added into Hermes, but this doesn't seem to be the case.

**Comment by greg-szabo** [comment]
> I would request one feature though: I'd expect when running `gm hermes keys` that all wallet* for each chain to be added into Hermes, but this doesn't seem to be the case.

That must be a bug, this worked for me. Can you show the commands you used so I can reproduce?

You might need to delete (`gm rm`) old networks and create them fresh.

**Comment by adizere** [comment]
> That must be a bug, this worked for me. Can you show the commands you used so I can reproduce?

Sure!

Using [gm.toml](https://gist.github.com/adizere/74136884a4ef33714e8684c9a77ad5aa)

```bash
$ gm version
v0.1.0

$ gm stop
Stopping ibc-0 with PID 9520...
Stopping ibc-1 with PID 9679...
Stopping node0 with PID 9892...
Stopping node1 with PID 10103...

$ gm status
NODE               PID    RPC   APP  GRPC  HOME_DIR
ibc-0                -      -     -     -  /Users/adi/.gm/ibc-0
 node0               -      -     -     -  /Users/adi/.gm/node0
ibc-1                -      -     -     -  /Users/adi/.gm/ibc-1
 node1               -      -     -     -  /Users/adi/.gm/node1

$ rm -rf ~/.gm/ibc-*
$ rm -rf ~/.gm/node*

-----
$ gm start
Creating ibc-0 config...
ibc-0 started, PID: 11164, LOG: /Users/adi/.gm/ibc-0/log
Creating ibc-1 config...
ibc-1 started, PID: 11327, LOG: /Users/adi/.gm/ibc-1/log
Creating node0 config...
node0 started, PID: 11539, LOG: /Users/adi/.gm/node0/log
Creating node1 config...
node1 started, PID: 11750, LOG: /Users/adi/.gm/node1/log

$ gm status
NODE               PID    RPC   APP  GRPC  HOME_DIR
ibc-0            11164  27000 27001 27002  /Users/adi/.gm/ibc-0
 node0           11539  27020 27021 27022  /Users/adi/.gm/node0
ibc-1            11327  27010 27011 27012  /Users/adi/.gm/ibc-1
 node1           11750  27030 27031 27032  /Users/adi/.gm/node1

$ ll ~/.gm/ibc-0/keyring-test/
Permissions Size User Date Modified Name
.rw-------   531 adi  30 Nov 16:48  7ce1a16148f8cb7cd4e77ec01f24bce82f5b8eca.address
.rw-------   531 adi  30 Nov 16:48  58adbbe3c27e804d98cf24c2f607704c5fd9414e.address
.rw-------   536 adi  30 Nov 16:48  a3e63358583f9b215e6526d0514c286257bb8da8.address
.rw-------   656 adi  30 Nov 16:48  validator.info
.rw-------   647 adi  30 Nov 16:48  wallet.info
.rw-------   648 adi  30 Nov 16:48  wallet1.info

# Cleaning up
$ rm -rf ~/.hermes/keys/ibc-0/keyring-test/*

$ gm hermes config
$ gm hermes keys
Success: Added key 'wallet' (cosmos10ns6zc2glr9he4880mqp7f9uaqh4hrk2rx8vgk) on chain ibc-0
Success: Added key 'wallet' (cosmos1hqsn4z3xqrcflwmjnkrelce236r2ey08a8ptnl) on chain ibc-1


$ ll ~/.hermes/keys/ibc-0/keyring-test/
Permissions Size User Date Modified Name
.rw-r--r--   520 adi  30 Nov 16:50  wallet.json

```

**Comment by adizere** [comment]
Had a quick look at the code, and my naive understanding it that this is not supported yet

https://github.com/informalsystems/ibc-rs/blob/26573d5a30e2d9c8772fde78696217c12578c0c7/scripts/gm/bin/lib-gm#L1009-L1023

**Comment by adizere** [comment]
Had a quick look at the code, and my naive understanding it that this is not supported yet

https://github.com/informalsystems/ibc-rs/blob/26573d5a30e2d9c8772fde78696217c12578c0c7/scripts/gm/bin/lib-gm#L1009-L1023

**Comment by greg-szabo** [comment]
You are right! I completely misunderstood you. I'm on it.

**Review by adizere — APPROVED** [review]
Wohoo!

> Success: Added key 'wallet' (cosmos12vga9atd4vrwmkefff6tpcdmtay6paapceycgs) on chain ibc-0
Success: Added key 'wallet2' (cosmos13un62d27jg3rnekewde00tyulflzz35pgshseg) on chain ibc-0
Success: Added key 'wallet1' (cosmos1hlvvyhzy5fjxs5r6kuw293wrsfracem788vtvu) on chain ibc-0
Success: Added key 'wallet' (cosmos13xewuzj05us2pzqcgcmj0u2t0s9ct45xt4nt5y) on chain ibc-1
Success: Added key 'wallet2' (cosmos1gt7kmjhx8z8v96e2t8elmffprdlgad0asak9h3) on chain ibc-1
Success: Added key 'wallet1' (cosmos1s9tmk02mwahzch9pcex2szvhawmx20gan72mf7) on chain ibc-1

**Pull request merged**
