### PR TITLE
Update to latest tendermint-rs and adapt relayer to new light client

### PR DESCRIPTION
**Pull request by romac**
Close: #243 
Close: #90

Depends on https://github.com/informalsystems/tendermint-rs/pull/583

## Description

______

For contributor use:

- [ ] Unit tests written
- [ ] Added test to CI if applicable 
- [ ] Updated CHANGELOG_PENDING.md
- [ ] Linked to Github issue with discussion and accepted design OR link to spec that describes this work.
- [ ] Updated relevant documentation (`docs/`) and code comments
- [ ] Re-reviewed `Files changed` in the Github PR explorer

### CODE REVIEW

**Comment by andynog** [comment]
Hi @romac, I've checked out your branch` romac/light-client-cleanup` and when I try cargo build I'm getting an error it can't find the `tendermint-rs/tendermint/Cargo.toml file`. 

```
~/dev/github.com/informalsystems/ibc-rs$ cargo build
error: failed to read `/home/andy/dev/github.com/informalsystems/tendermint-rs/tendermint/Cargo.toml`

Caused by:
  No such file or directory (os error 2)
```

On this machine I don't have tendermint-rs in the location it's trying to find it. I believe this is because in Cargo.toml the path is specified like this `tendermint = { version = "0.16.0", path = "../../tendermint-rs/tendermint" }` but should we have a repo dependency like this ? It assumes users would need to git clone tendermint-rs. 

Should we just have the version ?

**Comment by romac** [comment]
My bad, sorry about that! Will update it to use the tendermint-rs version from the branch in informalsystems/tendermint-rs#583.

**Comment by romac** [comment]
@andynog https://github.com/informalsystems/ibc-rs/pull/255/commits/4fecf8865a2f01c32fa6fe18da922317177cedd6

**Comment by romac** [comment]
Just to clarify, the git dependency is needed because this PR depends on these unreleased changes in tendermint-rs: https://github.com/informalsystems/tendermint-rs/pull/583

**Comment by andynog** [comment]
Hi @romac, it's building fine now. Thanks !

**Review by ancazamfir — APPROVED** [review]
Looks good to merge for now. The listen mode does not work but we should look into this later.

**Review by andynog — CHANGES_REQUESTED** [review]
I've run the tests again and I could configure both light clients for chain_A and chain_B, but when starting the relayer I'm getting a parse error. Not sure if it's related to the config TOML (the line it complains doesn't match with something in the config I think so maybe somewhere else). Here's the message:

```
(base) andy@ubuntu:~/dev/github.com/informalsystems/ibc-rs$ cargo run --bin relayer -- -c ./relayer/tests/config/fixtures/relayer_conf_example.toml start --reset
    Finished dev [unoptimized + debuginfo] target(s) in 0.20s
     Running `target/debug/relayer -c ./relayer/tests/config/fixtures/relayer_conf_example.toml start --reset`
Sep 30 10:58:40.686  INFO relayer_cli::commands::start: spawning light client chain.id=chain_A
     Relayer spawning light client for chain chain_A
Sep 30 10:58:40.828  INFO relayer_cli::commands::start: resetting client to trust options state chain.id=chain_A
error: relayer-cli fatal error: I/O error: Parse error. Invalid JSON: invalid type: string "1", expected u64 at line 17 column 24 (code: -32700)
```

**Comment by romac** [comment]
The `relayer start` command currently fails with a `relayer-cli fatal error: hash mismatch`.
This is due to a [bug in tendermint-rs](https://github.com/informalsystems/tendermint-rs/issues/600) that we just surfaced today.
As such, I don't think it should block the merge of this PR.

**Comment by romac** [comment]
We still need to wait for https://github.com/informalsystems/tendermint-rs/pull/583 to be merged first.

**Comment by andynog** [comment]
So I've updated the chains (chain_A and chain_B) to run with the latest stargate-3 version. Now there's another error. 

```
(base) andy@ubuntu:~/dev/github.com/informalsystems/ibc-rs$  cargo run --bin relayer -- -c ./relayer/tests/config/fixtures/relayer_conf_example.toml start --reset
    Finished dev [unoptimized + debuginfo] target(s) in 0.15s
     Running `target/debug/relayer -c ./relayer/tests/config/fixtures/relayer_conf_example.toml start --reset`
Sep 30 14:30:01.285  INFO relayer_cli::commands::start: spawning light client chain.id=chain_A
     Relayer spawning light client for chain chain_A
Sep 30 14:30:01.416  INFO relayer_cli::commands::start: resetting client to trust options state chain.id=chain_A
error: relayer-cli fatal error: I/O error: Parse error. Invalid JSON: missing field `app` at line 9 column 9 (code: -32700)
```

Not sure which JSON it's referring too, maybe it's a genesis.json for chain_A and somewhere there's a validation for that. Maybe this error is coming from other dependencies.

**Review by andynog — APPROVED** [review]
I think this is OK to merge, it's not failing on tests and it builds fine. I think the tests we have with chain are not in particular having issues related to this implementation. So I believe this is good to go.

**Pull request merged**
