### PR TITLE
Release 0.0.4 of ibc-rs

### PR DESCRIPTION
**Pull request by ancazamfir**
Closes: #271

### CODE REVIEW

**Review by andynog — APPROVED** [review]
I think this is good. I've checked all the closed issues list after 0.0.3 and all are in the changelog. The only thing I've noticed is that the release date is set to September 30 and previous releases we always used 1st day of the month so probably would make more sense to set it to October 1st to align with previous releases.

**Comment by ancazamfir** [comment]
> I think this is good. I've checked all the closed issues list after 0.0.3 and all are in the changelog. The only thing I've noticed is that the release date is set to September 30 and previous releases we always used 1st day of the month so probably would make more sense to set it to October 1st to align with previous releases.

This was planned for yesterday. We normally have the milestones end of month and initial thought was to have the release the same date (see v.0.0.1). But yes, 1st of the month looks better. We will probably not do it today though. But I will update the date once we are ready.

**Comment by romac** [comment]
Great release notes! 👍

**Comment by ancazamfir** [comment]
We should wait for tendermint v0.17 and update the dependencies and release notes with that.

**Pull request merged**
