### PR TITLE
Update scripts and dockerfiles to support gaia at stargate-4 version

### PR DESCRIPTION
**Pull request by andynog**
Closes: #278

## Description

Upgrade the docker images and chains to the latest stargate-4 version.

______

For contributor use:

- [ ] Unit tests written
- [ ] Added test to CI if applicable 
- [ ] Updated CHANGELOG_PENDING.md
- [X] Linked to Github issue with discussion and accepted design OR link to spec that describes this work.
- [ ] Updated relevant documentation (`docs/`) and code comments
- [ ] Re-reviewed `Files changed` in the Github PR explorer

### CODE REVIEW

**Review by adizere — APPROVED** [review]
Thanks Andy! To actually test this we need to update the images on Docker Hub, right?

**Comment by andynog** [comment]
I've tested this with the updated (local) Docker images and I cannot start the relayer. I get an error that I'm not sure is related to the images.

```
andy@lnx-01:~/Development/github.com/informalsystems/ibc-rs$ cargo run --bin relayer -- -c ./relayer/tests/config/fixtures/relayer_conf_example.toml light init -x "5F37C73284A9460D303EEFF4797D91886761E9D7506C38A4CB5A97EF79BDCA87" -h 347 chain_A
    Finished dev [unoptimized + debuginfo] target(s) in 0.10s
     Running `target/debug/relayer -c ./relayer/tests/config/fixtures/relayer_conf_example.toml light init -x 5F37C73284A9460D303EEFF4797D91886761E9D7506C38A4CB5A97EF79BDCA87 -h 347 chain_A`
     chain_A Set trusted options: hash=5F37C73284A9460D303EEFF4797D91886761E9D7506C38A4CB5A97EF79BDCA87 height=347
andy@lnx-01:~/Development/github.com/informalsystems/ibc-rs$ cargo run --bin relayer -- -c ./relayer/tests/config/fixtures/relayer_conf_example.toml light init -x "DCC609A432F98C48A268B4F631EBC7657807A0E2D41883A958B334A175CF6F97" -h 346 chain_B
    Finished dev [unoptimized + debuginfo] target(s) in 0.11s
     Running `target/debug/relayer -c ./relayer/tests/config/fixtures/relayer_conf_example.toml light init -x DCC609A432F98C48A268B4F631EBC7657807A0E2D41883A958B334A175CF6F97 -h 346 chain_B`
     chain_B Set trusted options: hash=DCC609A432F98C48A268B4F631EBC7657807A0E2D41883A958B334A175CF6F97 height=346
andy@lnx-01:~/Development/github.com/informalsystems/ibc-rs$ cargo run --bin relayer -- -c ./relayer/tests/config/fixtures/relayer_conf_example.toml start --reset
    Finished dev [unoptimized + debuginfo] target(s) in 0.11s
     Running `target/debug/relayer -c ./relayer/tests/config/fixtures/relayer_conf_example.toml start --reset`
Oct 06 13:52:48.747  INFO relayer_cli::commands::start: spawning light client chain.id=chain_A
     Relayer spawning light client for chain chain_A
Oct 06 13:52:48.889  INFO relayer_cli::commands::start: resetting client to trust options state chain.id=chain_A
error: relayer-cli fatal error: I/O error: Parse error. Invalid JSON: missing field `app` at line 9 column 9 (code: -32700)
```
I'm going to test this with the original images to see if I get the same error, if so then something that might have been introduced in the relayer logic that might be breaking.

**Comment by andynog** [comment]
After tendermint-rs fix #622, the error above `missing field app` is not happening anymore. Now getting a hash mismatch error. Here spinning two-chains using the `dev-env` script from go relayer (but the same error happens using docker images). One common variable between these two environments is that they use a startgate-3 branch.

```
$> curl -s http://localhost:26657/status | jq '.result.sync_info|.latest_block_hash,.latest_block_height'
"73538125C2540CA1DC9DF6E28C295E46B5214D5A800D1AA6327228C62F0A526F"
"2133"
```
```
$> cargo run --bin relayer -- -c ./relayer-cli/tests/fixtures/two_chains.toml light init -x "73538125C2540CA1DC9DF6E28C295E46B5214D5A800D1AA6327228C62F0A526F" -h 2133 ibc0
    Finished dev [unoptimized + debuginfo] target(s) in 0.14s
     Running `target/debug/relayer -c ./relayer-cli/tests/fixtures/two_chains.toml light init -x 73538125C2540CA1DC9DF6E28C295E46B5214D5A800D1AA6327228C62F0A526F -h 2133 ibc0`
        ibc0 Set trusted options: hash=73538125C2540CA1DC9DF6E28C295E46B5214D5A800D1AA6327228C62F0A526F height=2133
```
```
$> curl -s http://localhost:26557/status | jq '.result.sync_info|.latest_block_hash,.latest_block_height'
"9B2B144DCCC052228B3E58171F645A1973CD7AD92ACEA69CEE5BB881453DC1FD"
"2211"
```
```
cargo run --bin relayer -- -c ./relayer-cli/tests/fixtures/two_chains.toml light init -x "9B2B144DCCC052228B3E58171F645A1973CD7AD92ACEA69CEE5BB881453DC1FD" -h 2211 ibc1
    Finished dev [unoptimized + debuginfo] target(s) in 0.14s
     Running `target/debug/relayer -c ./relayer-cli/tests/fixtures/two_chains.toml light init -x 9B2B144DCCC052228B3E58171F645A1973CD7AD92ACEA69CEE5BB881453DC1FD -h 2211 ibc1`
        ibc1 Set trusted options: hash=9B2B144DCCC052228B3E58171F645A1973CD7AD92ACEA69CEE5BB881453DC1FD height=2211
```
```
$> cargo run --bin relayer -- -c ./relayer-cli/tests/fixtures/two_chains.toml start --reset
    Finished dev [unoptimized + debuginfo] target(s) in 0.13s
     Running `target/debug/relayer -c ./relayer-cli/tests/fixtures/two_chains.toml start --reset`
Oct 08 17:15:59.779  INFO relayer_cli::commands::start: spawning light client chain.id=ibc0
     Relayer spawning light client for chain ibc0
Oct 08 17:15:59.930  INFO relayer_cli::commands::start: resetting client to trust options state chain.id=ibc0
error: relayer-cli fatal error: hash mismatch: given = 73538125C2540CA1DC9DF6E28C295E46B5214D5A800D1AA6327228C62F0A526F, found = 1661F082AC04E73A45390636B090194932DA3660706CD24EABC3DCFA8A1BAF06
```

If I query the block `2133` for ibc0 chain, I get the right hash at that height `73538125C2540CA1DC9DF6E28C295E46B5214D5A800D1AA6327228C62F0A526F`

```
$> curl http://localhost:26657/block?height=2133
```

```
{
  "jsonrpc": "2.0",
  "id": -1,
  "result": {
    "block_id": {
      "hash": "73538125C2540CA1DC9DF6E28C295E46B5214D5A800D1AA6327228C62F0A526F",
      "parts": {
        "total": 1,
        "hash": "D7CE116964172EDA4829E107F02A87D6F960A8EC08DC86FF4ADB3A782D605B06"
      }
    },
...
```

So not sure why the relayer is spitting out a hash mismatch.

**Comment by andynog** [comment]
Test it again using the go relayer dev-env script after master changes (#299). Now I'm getting another error

```
cargo run --bin relayer -- -c ./relayer-cli/tests/fixtures/two_chains.toml start --reset
    Finished dev [unoptimized + debuginfo] target(s) in 0.11s
     Running `target/debug/relayer -c ./relayer-cli/tests/fixtures/two_chains.toml start --reset`
Oct 09 12:14:23.505  INFO relayer_cli::commands::start: spawning light client chain.id=ibc0
     Relayer spawning light client for chain ibc0
Oct 09 12:14:23.642  INFO relayer_cli::commands::start: resetting client to trust options state chain.id=ibc0
Oct 09 12:14:23.664  INFO relayer_cli::commands::start: resetting client to trust options state chain.id=ibc0
The application panicked (crashed).
Message:  Pre-condition of witness violated: self . primary != Some(peer_id)
Location: /home/andy/.cargo/git/checkouts/tendermint-rs-7b2e4433a0119a31/0681df8/light-client/src/peer_list.rs:202

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.
```

**Comment by romac** [comment]
This error means that we are setting both the primary's and witness' peer id to the same value. It stems from the fact that we don't have peer ids in the relayer config and we currently have [to make one up](https://github.com/informalsystems/ibc-rs/blob/e3a8384830850a3837bc9aa31bd8cfe2bd7c34a3/relayer-cli/src/commands/start.rs#L185). The issue is that we re-use it for both the primary and the witness, whereas we should at least make up two different ones until we decide on whether we want to add peer ids to the config, or get rid of them altogether.

**Review by greg-szabo — APPROVED** [review]

**Comment by ancazamfir** [comment]
Since this is not closed, could we actually move to stargate-4. Our code base is currently compatible with 4 and we could use these scripts to run queries and Tx-es hopefully soon :)

**Review by ancazamfir — APPROVED** [review]
Wohooo! Thanks Andy!

**Comment by andynog** [comment]
Tested docker images with gaia stargate-4 and it's working now after latest fix. Good to merge. Ran the commands (from README) to initialize light clients and start the relayer and it's working.

**Pull request merged**
