### PR TITLE
Add guide changes slated for 0.14 release

### PR DESCRIPTION
**Pull request by seanchen1991**
Accompanying guide changes for #2014.

## Description

#2014 changes the user flow of the `create channel` CLI command. This PR updates the Hermes guide to reflect the new user flow when using this command. 

______

### PR author checklist:
- [ ] Added changelog entry, using [`unclog`](https://github.com/informalsystems/unclog).
- [ ] Added tests: integration (for Hermes) or unit/mock tests (for modules). 
- [ ] Linked to GitHub issue.
- [ ] Updated code comments and documentation (e.g., `docs/`).

### Reviewer checklist:

- [ ] Reviewed `Files changed` in the GitHub PR explorer.
- [ ] Manually tested (in case integration/unit/mock tests are absent).

### CODE REVIEW

**Comment by seanchen1991** [comment]
Should PRs that only update the Hermes guide come with a changelog entry?

**Comment by mzabaluev** [comment]
> Should PRs that only update the Hermes guide come with a changelog entry?

Probably not, there's no value for the software user in a separate entry that's just going to refer to changes otherwise present in the changelog.

**Review by mzabaluev — APPROVED** [review]
A good update.

One deficiency with the guide now, it encourages to reuse an existing client/connection when creating a channel, without providing step-by-step examples on how to set these entities up with dedicated commands.

**Comment by romac** [comment]
Thanks! Sorry for the churn, but now that #2082 is in, we can actually merge this before the release :)

**Pull request merged**
