### PR TITLE
fix tendermint dependencies

### PR DESCRIPTION
**Pull request by ancazamfir**
## Description
tendermint dependencies need update after merge of #255

### CODE REVIEW

**Review by andynog — COMMENTED** [review]
Do we really need to keep the git property or should we just use version? Was the git introduced in order to specify the brach? In the past we had

tendermint = "0.15.0"

**Comment by ancazamfir** [comment]
> Do we really need to keep the git property or should we just use version? Was the git introduced in order to specify the brach? In the past we had
> 
> tendermint = "0.15.0"

We will move to 0.17 once it's out, hopefully in a few days. But now we need the fix from  https://github.com/informalsystems/tendermint-rs/pull/583 (on top of 0.16.0). Also maybe other commits that will go in master before 0.17 is released.

**Comment by andynog** [comment]
Makes sense since there's a dependency on #583 until 0.17 release

**Review by andynog — APPROVED** [review]
Looks good!

**Pull request merged**
