### PR TITLE
CLI auto-completions

### PR DESCRIPTION
**Pull request by mzabaluev**
Closes: #1096

## Description

Add a `completions` command using the functionality of `clap_complete` to generate completion scripts for various shells.

______

### PR author checklist:
- [x] Added changelog entry, using [`unclog`](https://github.com/informalsystems/unclog).
- [ ] Added tests: integration (for Hermes) or unit/mock tests (for modules). 
- [x] Linked to GitHub issue.
- [ ] Updated code comments and documentation (e.g., `docs/`).

### Reviewer checklist:

- [ ] Reviewed `Files changed` in the GitHub PR explorer.
- [ ] Manually tested (in case integration/unit/mock tests are absent).

### CODE REVIEW

**Comment by mzabaluev** [comment]
Thanks @rnbguy for providing a code example and the timely release of modelator to enable a clap upgrade!

**Comment by mzabaluev** [comment]
I have tested that it works with bash.

**Review by romac — APPROVED** [review]

**Comment by romac** [comment]
Couldn't make it work with zsh but that's likely an issue with my setup (my dotfiles are a mess). In any case, this mostly piggy backs on `clap` so we should be good to go.

**Comment by rnbguy** [comment]
@romac where are you putting the generated completions scripts for `zsh`?

**Pull request merged**
